(function(){var m;function aa(a){var b=0;return function(){return b<a.length?{done:!1,value:a[b++]}:{done:!0}}}function ba(a){var b="undefined"!=typeof Symbol&&Symbol.iterator&&a[Symbol.iterator];return b?b.call(a):{next:aa(a)}}function ca(a){for(var b,c=[];!(b=a.next()).done;)c.push(b.value);return c}var da="undefined"!=typeof window&&window===this?this:"undefined"!=typeof global&&null!=global?global:this;/*

 Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
(function(a){function b(a,b){if("function"===typeof window.CustomEvent)return new CustomEvent(a,b);var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c}function c(a){if(S)return a.ownerDocument!==document?a.ownerDocument:null;var b=a.__importDoc;if(!b&&a.parentNode){b=a.parentNode;if("function"===typeof b.closest)b=b.closest("link[rel=import]");else for(;!h(b)&&(b=b.parentNode););a.__importDoc=b}return b}function d(a){var b=n(document,"link[rel=import]:not([import-dependency])"),
c=b.length;c?q(b,function(b){return g(b,function(){0===--c&&a()})}):a()}function e(a){function b(){"loading"!==document.readyState&&document.body&&(document.removeEventListener("readystatechange",b),a())}document.addEventListener("readystatechange",b);b()}function f(a){e(function(){return d(function(){return a&&a()})})}function g(a,b){if(a.__loaded)b&&b();else if("script"===a.localName&&!a.src||"style"===a.localName&&!a.firstChild)a.__loaded=!0,b&&b();else{var c=function(d){a.removeEventListener(d.type,
c);a.__loaded=!0;b&&b()};a.addEventListener("load",c);ia&&"style"===a.localName||a.addEventListener("error",c)}}function h(a){return a.nodeType===Node.ELEMENT_NODE&&"link"===a.localName&&"import"===a.rel}function k(){var a=this;this.F={};this.T=0;this.Ca=new MutationObserver(function(b){return a.tc(b)});this.Ca.observe(document.head,{childList:!0,subtree:!0});this.loadImports(document)}function l(a){q(n(a,"template"),function(a){q(n(a.content,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]'),
function(a){var b=document.createElement("script");q(a.attributes,function(a){return b.setAttribute(a.name,a.value)});b.textContent=a.textContent;a.parentNode.replaceChild(b,a)});l(a.content)})}function n(a,b){return a.childNodes.length?a.querySelectorAll(b):eb}function q(a,b,c){var d=a?a.length:0,e=c?-1:1;for(c=c?d-1:0;c<d&&0<=c;c+=e)b(a[c],c)}var v=document.createElement("link"),S="import"in v,eb=v.querySelectorAll("*"),ra=null;!1==="currentScript"in document&&Object.defineProperty(document,"currentScript",
{get:function(){return ra||("complete"!==document.readyState?document.scripts[document.scripts.length-1]:null)},configurable:!0});var fb=/(url\()([^)]*)(\))/g,gb=/(@import[\s]+(?!url\())([^;]*)(;)/g,T=/(<link[^>]*)(rel=['|"]?stylesheet['|"]?[^>]*>)/g,D={rc:function(a,b){a.href&&a.setAttribute("href",D.ka(a.getAttribute("href"),b));a.src&&a.setAttribute("src",D.ka(a.getAttribute("src"),b));if("style"===a.localName){var c=D.lb(a.textContent,b,fb);a.textContent=D.lb(c,b,gb)}},lb:function(a,b,c){return a.replace(c,
function(a,c,d,e){a=d.replace(/["']/g,"");b&&(a=D.ka(a,b));return c+"'"+a+"'"+e})},ka:function(a,b){if(void 0===D.oa){D.oa=!1;try{var c=new URL("b","http://a");c.pathname="c%20d";D.oa="http://a/c%20d"===c.href}catch(tc){}}if(D.oa)return(new URL(a,b)).href;c=D.vb;c||(c=document.implementation.createHTMLDocument("temp"),D.vb=c,c.Ia=c.createElement("base"),c.head.appendChild(c.Ia),c.Ha=c.createElement("a"));c.Ia.href=b;c.Ha.href=a;return c.Ha.href||a}},X={async:!0,load:function(a,b,c){if(a)if(a.match(/^data:/)){a=
a.split(",");var d=a[1];d=-1<a[0].indexOf(";base64")?atob(d):decodeURIComponent(d);b(d)}else{var e=new XMLHttpRequest;e.open("GET",a,X.async);e.onload=function(){var a=e.responseURL||e.getResponseHeader("Location");a&&0===a.indexOf("/")&&(a=(location.origin||location.protocol+"//"+location.host)+a);var d=e.response||e.responseText;304===e.status||0===e.status||200<=e.status&&300>e.status?b(d,a):c(d)};e.send()}else c("error: href must be specified")}},ia=/Trident/.test(navigator.userAgent)||/Edge\/\d./i.test(navigator.userAgent);
k.prototype.loadImports=function(a){var b=this;a=n(a,"link[rel=import]");q(a,function(a){return b.hb(a)})};k.prototype.hb=function(a){var b=this,c=a.href;if(void 0!==this.F[c]){var d=this.F[c];d&&d.__loaded&&(a.__import=d,this.fb(a))}else this.T++,this.F[c]="pending",X.load(c,function(a,d){a=b.zc(a,d||c);b.F[c]=a;b.T--;b.loadImports(a);b.jb()},function(){b.F[c]=null;b.T--;b.jb()})};k.prototype.zc=function(a,b){if(!a)return document.createDocumentFragment();ia&&(a=a.replace(T,function(a,b,c){return-1===
a.indexOf("type=")?b+" type=import-disable "+c:a}));var c=document.createElement("template");c.innerHTML=a;if(c.content)a=c.content,l(a);else for(a=document.createDocumentFragment();c.firstChild;)a.appendChild(c.firstChild);if(c=a.querySelector("base"))b=D.ka(c.getAttribute("href"),b),c.removeAttribute("href");c=n(a,'link[rel=import],link[rel=stylesheet][href][type=import-disable],style:not([type]),link[rel=stylesheet][href]:not([type]),script:not([type]),script[type="application/javascript"],script[type="text/javascript"],script[type="module"]');
var d=0;q(c,function(a){g(a);D.rc(a,b);a.setAttribute("import-dependency","");if("script"===a.localName&&!a.src&&a.textContent){if("module"===a.type)throw Error("Inline module scripts are not supported in HTML Imports.");a.setAttribute("src","data:text/javascript;charset=utf-8,"+encodeURIComponent(a.textContent+("\n//# sourceURL="+b+(d?"-"+d:"")+".js\n")));a.textContent="";d++}});return a};k.prototype.jb=function(){var a=this;if(!this.T){this.Ca.disconnect();this.flatten(document);var b=!1,c=!1,d=
function(){c&&b&&(a.loadImports(document),a.T||(a.Ca.observe(document.head,{childList:!0,subtree:!0}),a.qc()))};this.Mc(function(){c=!0;d()});this.Ec(function(){b=!0;d()})}};k.prototype.flatten=function(a){var b=this;a=n(a,"link[rel=import]");q(a,function(a){var c=b.F[a.href];(a.__import=c)&&c.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&(b.F[a.href]=a,a.readyState="loading",a.__import=a,b.flatten(c),a.appendChild(c))})};k.prototype.Ec=function(a){function b(e){if(e<d){var f=c[e],h=document.createElement("script");
f.removeAttribute("import-dependency");q(f.attributes,function(a){return h.setAttribute(a.name,a.value)});ra=h;f.parentNode.replaceChild(h,f);g(h,function(){ra=null;b(e+1)})}else a()}var c=n(document,"script[import-dependency]"),d=c.length;b(0)};k.prototype.Mc=function(a){var b=n(document,"style[import-dependency],link[rel=stylesheet][import-dependency]"),d=b.length;if(d){var e=ia&&!!document.querySelector("link[rel=stylesheet][href][type=import-disable]");q(b,function(b){g(b,function(){b.removeAttribute("import-dependency");
0===--d&&a()});if(e&&b.parentNode!==document.head){var f=document.createElement(b.localName);f.__appliedElement=b;f.setAttribute("type","import-placeholder");b.parentNode.insertBefore(f,b.nextSibling);for(f=c(b);f&&c(f);)f=c(f);f.parentNode!==document.head&&(f=null);document.head.insertBefore(b,f);b.removeAttribute("type")}})}else a()};k.prototype.qc=function(){var a=this,b=n(document,"link[rel=import]");q(b,function(b){return a.fb(b)},!0)};k.prototype.fb=function(a){a.__loaded||(a.__loaded=!0,a["import"]&&
(a["import"].readyState="complete"),a.dispatchEvent(b(a["import"]?"load":"error",{bubbles:!1,cancelable:!1,detail:void 0})))};k.prototype.tc=function(a){var b=this;q(a,function(a){return q(a.addedNodes,function(a){a&&a.nodeType===Node.ELEMENT_NODE&&(h(a)?b.hb(a):b.loadImports(a))})})};var sa=null;if(S)v=n(document,"link[rel=import]"),q(v,function(a){a["import"]&&"loading"===a["import"].readyState||(a.__loaded=!0)}),v=function(a){a=a.target;h(a)&&(a.__loaded=!0)},document.addEventListener("load",v,
!0),document.addEventListener("error",v,!0);else{var Z=Object.getOwnPropertyDescriptor(Node.prototype,"baseURI");Object.defineProperty((!Z||Z.configurable?Node:Element).prototype,"baseURI",{get:function(){var a=h(this)?this:c(this);return a?a.href:Z&&Z.get?Z.get.call(this):(document.querySelector("base")||window.location).href},configurable:!0,enumerable:!0});Object.defineProperty(HTMLLinkElement.prototype,"import",{get:function(){return this.__import||null},configurable:!0,enumerable:!0});e(function(){sa=
new k})}f(function(){return document.dispatchEvent(b("HTMLImportsLoaded",{cancelable:!0,bubbles:!0,detail:void 0}))});a.useNative=S;a.whenReady=f;a.importForElement=c;a.loadImports=function(a){sa&&sa.loadImports(a)}})(window.HTMLImports=window.HTMLImports||{});(function(){function a(){}function b(a,b){if(!a.childNodes.length)return[];switch(a.nodeType){case Node.DOCUMENT_NODE:return ra.call(a,b);case Node.DOCUMENT_FRAGMENT_NODE:return fb.call(a,b);default:return eb.call(a,b)}}var c="undefined"===typeof HTMLTemplateElement,d=!(document.createDocumentFragment().cloneNode()instanceof DocumentFragment),e=!1;/Trident/.test(navigator.userAgent)&&function(){function a(a,b){if(a instanceof DocumentFragment)for(var d;d=a.firstChild;)c.call(this,d,b);else c.call(this,
a,b);return a}e=!0;var b=Node.prototype.cloneNode;Node.prototype.cloneNode=function(a){a=b.call(this,a);this instanceof DocumentFragment&&(a.__proto__=DocumentFragment.prototype);return a};DocumentFragment.prototype.querySelectorAll=HTMLElement.prototype.querySelectorAll;DocumentFragment.prototype.querySelector=HTMLElement.prototype.querySelector;Object.defineProperties(DocumentFragment.prototype,{nodeType:{get:function(){return Node.DOCUMENT_FRAGMENT_NODE},configurable:!0},localName:{get:function(){},
configurable:!0},nodeName:{get:function(){return"#document-fragment"},configurable:!0}});var c=Node.prototype.insertBefore;Node.prototype.insertBefore=a;var d=Node.prototype.appendChild;Node.prototype.appendChild=function(b){b instanceof DocumentFragment?a.call(this,b,null):d.call(this,b);return b};var f=Node.prototype.removeChild,g=Node.prototype.replaceChild;Node.prototype.replaceChild=function(b,c){b instanceof DocumentFragment?(a.call(this,b,c),f.call(this,c)):g.call(this,b,c);return c};Document.prototype.createDocumentFragment=
function(){var a=this.createElement("df");a.__proto__=DocumentFragment.prototype;return a};var h=Document.prototype.importNode;Document.prototype.importNode=function(a,b){b=h.call(this,a,b||!1);a instanceof DocumentFragment&&(b.__proto__=DocumentFragment.prototype);return b}}();var f=Node.prototype.cloneNode,g=Document.prototype.createElement,h=Document.prototype.importNode,k=Node.prototype.removeChild,l=Node.prototype.appendChild,n=Node.prototype.replaceChild,q=DOMParser.prototype.parseFromString,
v=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML")||{get:function(){return this.innerHTML},set:function(a){this.innerHTML=a}},S=Object.getOwnPropertyDescriptor(window.Node.prototype,"childNodes")||{get:function(){return this.childNodes}},eb=Element.prototype.querySelectorAll,ra=Document.prototype.querySelectorAll,fb=DocumentFragment.prototype.querySelectorAll,gb=function(){if(!c){var a=document.createElement("template"),b=document.createElement("template");b.content.appendChild(document.createElement("div"));
a.content.appendChild(b);a=a.cloneNode(!0);return 0===a.content.childNodes.length||0===a.content.firstChild.content.childNodes.length||d}}();if(c){var T=document.implementation.createHTMLDocument("template"),D=!0,X=document.createElement("style");X.textContent="template{display:none;}";var ia=document.head;ia.insertBefore(X,ia.firstElementChild);a.prototype=Object.create(HTMLElement.prototype);var sa=!document.createElement("div").hasOwnProperty("innerHTML");a.K=function(b){if(!b.content&&b.namespaceURI===
document.documentElement.namespaceURI){b.content=T.createDocumentFragment();for(var c;c=b.firstChild;)l.call(b.content,c);if(sa)b.__proto__=a.prototype;else if(b.cloneNode=function(b){return a.qa(this,b)},D)try{rc(b),sc(b)}catch(Fg){D=!1}a.D(b.content)}};var Z={option:["select"],thead:["table"],col:["colgroup","table"],tr:["tbody","table"],th:["tr","tbody","table"],td:["tr","tbody","table"]},rc=function(b){Object.defineProperty(b,"innerHTML",{get:function(){return hb(this)},set:function(b){var c=
Z[(/<([a-z][^/\0>\x20\t\r\n\f]+)/i.exec(b)||["",""])[1].toLowerCase()];if(c)for(var d=0;d<c.length;d++)b="<"+c[d]+">"+b+"</"+c[d]+">";T.body.innerHTML=b;for(a.D(T);this.content.firstChild;)k.call(this.content,this.content.firstChild);b=T.body;if(c)for(d=0;d<c.length;d++)b=b.lastChild;for(;b.firstChild;)l.call(this.content,b.firstChild)},configurable:!0})},sc=function(a){Object.defineProperty(a,"outerHTML",{get:function(){return"<template>"+this.innerHTML+"</template>"},set:function(a){if(this.parentNode){T.body.innerHTML=
a;for(a=this.ownerDocument.createDocumentFragment();T.body.firstChild;)l.call(a,T.body.firstChild);n.call(this.parentNode,a,this)}else throw Error("Failed to set the 'outerHTML' property on 'Element': This element has no parent node.");},configurable:!0})};rc(a.prototype);sc(a.prototype);a.D=function(c){c=b(c,"template");for(var d=0,e=c.length,f;d<e&&(f=c[d]);d++)a.K(f)};document.addEventListener("DOMContentLoaded",function(){a.D(document)});Document.prototype.createElement=function(){var b=g.apply(this,
arguments);"template"===b.localName&&a.K(b);return b};DOMParser.prototype.parseFromString=function(){var b=q.apply(this,arguments);a.D(b);return b};Object.defineProperty(HTMLElement.prototype,"innerHTML",{get:function(){return hb(this)},set:function(b){v.set.call(this,b);a.D(this)},configurable:!0,enumerable:!0});var De=/[&\u00A0"]/g,tc=/[&\u00A0<>]/g,uc=function(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}};
X=function(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b};var Ee=X("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Fe=X("style script xmp iframe noembed noframes plaintext noscript".split(" ")),hb=function(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):S.get.call(a),e=0,f=d.length,g;e<f&&(g=d[e]);e++){a:{var h=g;var k=a;var l=b;switch(h.nodeType){case Node.ELEMENT_NODE:for(var n=h.localName,q="<"+n,v=h.attributes,vc=0;k=
v[vc];vc++)q+=" "+k.name+'="'+k.value.replace(De,uc)+'"';q+=">";h=Ee[n]?q:q+hb(h,l)+"</"+n+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Fe[k.localName]?h:h.replace(tc,uc);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),Error("not implemented");}}c+=h}return c}}if(c||gb){a.qa=function(a,b){var c=f.call(a,!1);this.K&&this.K(c);b&&(l.call(c.content,f.call(a.content,!0)),ib(c.content,a.content));return c};var ib=function(c,d){if(d.querySelectorAll&&
(d=b(d,"template"),0!==d.length)){c=b(c,"template");for(var e=0,f=c.length,g,h;e<f;e++)h=d[e],g=c[e],a&&a.K&&a.K(h),n.call(g.parentNode,Ge.call(h,!0),g)}},Ge=Node.prototype.cloneNode=function(b){if(!e&&d&&this instanceof DocumentFragment)if(b)var c=He.call(this.ownerDocument,this,!0);else return this.ownerDocument.createDocumentFragment();else c=this.nodeType===Node.ELEMENT_NODE&&"template"===this.localName&&this.namespaceURI==document.documentElement.namespaceURI?a.qa(this,b):f.call(this,b);b&&ib(c,
this);return c},He=Document.prototype.importNode=function(c,d){d=d||!1;if("template"===c.localName)return a.qa(c,d);var e=h.call(this,c,d);if(d){ib(e,c);c=b(e,'script:not([type]),script[type="application/javascript"],script[type="text/javascript"]');for(var f,k=0;k<c.length;k++){f=c[k];d=g.call(document,"script");d.textContent=f.textContent;for(var l=f.attributes,q=0,v;q<l.length;q++)v=l[q],d.setAttribute(v.name,v.value);n.call(f.parentNode,d,f)}}return e}}c&&(window.HTMLTemplateElement=a)})();(function(){if(!function(){var a=document.createEvent("Event");a.initEvent("foo",!0,!0);a.preventDefault();return a.defaultPrevented}()){var a=Event.prototype.preventDefault;Event.prototype.preventDefault=function(){this.cancelable&&(a.call(this),Object.defineProperty(this,"defaultPrevented",{get:function(){return!0},configurable:!0}))}}var b=/Trident/.test(navigator.userAgent);if(!window.Event||b&&"function"!==typeof window.Event){var c=window.Event;window.Event=function(a,b){b=b||{};var c=document.createEvent("Event");
c.initEvent(a,!!b.bubbles,!!b.cancelable);return c};if(c){for(var d in c)window.Event[d]=c[d];window.Event.prototype=c.prototype}}if(!window.CustomEvent||b&&"function"!==typeof window.CustomEvent)window.CustomEvent=function(a,b){b=b||{};var c=document.createEvent("CustomEvent");c.initCustomEvent(a,!!b.bubbles,!!b.cancelable,b.detail);return c},window.CustomEvent.prototype=window.Event.prototype;if(!window.MouseEvent||b&&"function"!==typeof window.MouseEvent){b=window.MouseEvent;window.MouseEvent=
function(a,b){b=b||{};var c=document.createEvent("MouseEvent");c.initMouseEvent(a,!!b.bubbles,!!b.cancelable,b.view||window,b.detail,b.screenX,b.screenY,b.clientX,b.clientY,b.ctrlKey,b.altKey,b.shiftKey,b.metaKey,b.button,b.relatedTarget);return c};if(b)for(d in b)window.MouseEvent[d]=b[d];window.MouseEvent.prototype=b.prototype}Array.from||(Array.from=function(a){return[].slice.call(a)});Object.assign||(Object.assign=function(a,b){for(var c=[].slice.call(arguments,1),d=0,e;d<c.length;d++)if(e=c[d])for(var f=
a,n=e,q=Object.getOwnPropertyNames(n),v=0;v<q.length;v++)e=q[v],f[e]=n[e];return a})})();/*


 Copyright (c) 2014 Taylor Hakes
 Copyright (c) 2014 Forbes Lindesay

 Permission is hereby granted, free of charge, to any person obtaining a copy
 of this software and associated documentation files (the "Software"), to deal
 in the Software without restriction, including without limitation the rights
 to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 copies of the Software, and to permit persons to whom the Software is
 furnished to do so, subject to the following conditions:

 The above copyright notice and this permission notice shall be included in
 all copies or substantial portions of the Software.

 THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 THE SOFTWARE.
*/
var ea=setTimeout;function fa(){}function ha(a,b){return function(){a.apply(b,arguments)}}function p(a){if(!(this instanceof p))throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this.u=0;this.Ra=!1;this.f=void 0;this.O=[];ja(a,this)}
function ka(a,b){for(;3===a.u;)a=a.f;0===a.u?a.O.push(b):(a.Ra=!0,la(function(){var c=1===a.u?b.Ac:b.Bc;if(null===c)(1===a.u?ma:na)(b.Fa,a.f);else{try{var d=c(a.f)}catch(e){na(b.Fa,e);return}ma(b.Fa,d)}}))}function ma(a,b){try{if(b===a)throw new TypeError("A promise cannot be resolved with itself.");if(b&&("object"===typeof b||"function"===typeof b)){var c=b.then;if(b instanceof p){a.u=3;a.f=b;oa(a);return}if("function"===typeof c){ja(ha(c,b),a);return}}a.u=1;a.f=b;oa(a)}catch(d){na(a,d)}}
function na(a,b){a.u=2;a.f=b;oa(a)}function oa(a){2===a.u&&0===a.O.length&&la(function(){a.Ra||"undefined"!==typeof console&&console&&console.warn("Possible Unhandled Promise Rejection:",a.f)});for(var b=0,c=a.O.length;b<c;b++)ka(a,a.O[b]);a.O=null}function pa(a,b,c){this.Ac="function"===typeof a?a:null;this.Bc="function"===typeof b?b:null;this.Fa=c}function ja(a,b){var c=!1;try{a(function(a){c||(c=!0,ma(b,a))},function(a){c||(c=!0,na(b,a))})}catch(d){c||(c=!0,na(b,d))}}
p.prototype["catch"]=function(a){return this.then(null,a)};p.prototype.then=function(a,b){var c=new this.constructor(fa);ka(this,new pa(a,b,c));return c};p.prototype["finally"]=function(a){var b=this.constructor;return this.then(function(c){return b.resolve(a()).then(function(){return c})},function(c){return b.resolve(a()).then(function(){return b.reject(c)})})};
function qa(a){return new p(function(b,c){function d(a,g){try{if(g&&("object"===typeof g||"function"===typeof g)){var h=g.then;if("function"===typeof h){h.call(g,function(b){d(a,b)},c);return}}e[a]=g;0===--f&&b(e)}catch(n){c(n)}}if(!a||"undefined"===typeof a.length)throw new TypeError("Promise.all accepts an array");var e=Array.prototype.slice.call(a);if(0===e.length)return b([]);for(var f=e.length,g=0;g<e.length;g++)d(g,e[g])})}
function ta(a){return a&&"object"===typeof a&&a.constructor===p?a:new p(function(b){b(a)})}function ua(a){return new p(function(b,c){c(a)})}function va(a){return new p(function(b,c){for(var d=0,e=a.length;d<e;d++)a[d].then(b,c)})}var la="function"===typeof setImmediate&&function(a){setImmediate(a)}||function(a){ea(a,0)};/*

Copyright (c) 2017 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
if(!window.Promise){window.Promise=p;p.prototype.then=p.prototype.then;p.all=qa;p.race=va;p.resolve=ta;p.reject=ua;var wa=document.createTextNode(""),xa=[];(new MutationObserver(function(){for(var a=xa.length,b=0;b<a;b++)xa[b]();xa.splice(0,a)})).observe(wa,{characterData:!0});la=function(a){xa.push(a);wa.textContent=0<wa.textContent.length?"":"a"}};/*

 Copyright (c) 2014 The Polymer Project Authors. All rights reserved.
 This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
 The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
 The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
 Code distributed by Google as part of the polymer project is also
 subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
window.WebComponents=window.WebComponents||{flags:{}};var ya=document.querySelector('script[src*="webcomponents-lite.js"]'),za=/wc-(.+)/,r={};if(!r.noOpts){location.search.slice(1).split("&").forEach(function(a){a=a.split("=");var b;a[0]&&(b=a[0].match(za))&&(r[b[1]]=a[1]||!0)});if(ya)for(var Aa=0,Ba=void 0;Ba=ya.attributes[Aa];Aa++)"src"!==Ba.name&&(r[Ba.name]=Ba.value||!0);if(r.log&&r.log.split){var Ca=r.log.split(",");r.log={};Ca.forEach(function(a){r.log[a]=!0})}else r.log={}}
window.WebComponents.flags=r;var Da=r.shadydom;Da&&(window.ShadyDOM=window.ShadyDOM||{},window.ShadyDOM.force=Da);var Ea=r.register||r.ce;Ea&&window.customElements&&(window.customElements.forcePolyfill=Ea);/*

Copyright (c) 2016 The Polymer Project Authors. All rights reserved.
This code may only be used under the BSD style license found at http://polymer.github.io/LICENSE.txt
The complete set of authors may be found at http://polymer.github.io/AUTHORS.txt
The complete set of contributors may be found at http://polymer.github.io/CONTRIBUTORS.txt
Code distributed by Google as part of the polymer project is also
subject to an additional IP rights grant found at http://polymer.github.io/PATENTS.txt
*/
function Fa(){this.kb=this.root=null;this.ia=!1;this.G=this.ca=this.xa=this.assignedSlot=this.assignedNodes=this.L=null;this.childNodes=this.nextSibling=this.previousSibling=this.lastChild=this.firstChild=this.parentNode=this.U=void 0;this.rb=this.Ka=!1;this.Z={}}Fa.prototype.toJSON=function(){return{}};function t(a){a.__shady||(a.__shady=new Fa);return a.__shady}function u(a){return a&&a.__shady};var w=window.ShadyDOM||{};w.uc=!(!Element.prototype.attachShadow||!Node.prototype.getRootNode);var Ga=Object.getOwnPropertyDescriptor(Node.prototype,"firstChild");w.v=!!(Ga&&Ga.configurable&&Ga.get);w.Da=w.force||!w.uc;var Ha=navigator.userAgent.match("Trident"),Ia=navigator.userAgent.match("Edge");void 0===w.ob&&(w.ob=w.v&&(Ha||Ia));function Ja(a){return(a=u(a))&&void 0!==a.firstChild}function x(a){return"ShadyRoot"===a.Sb}function Ka(a){a=a.getRootNode();if(x(a))return a}
var La=Element.prototype,Ma=La.matches||La.matchesSelector||La.mozMatchesSelector||La.msMatchesSelector||La.oMatchesSelector||La.webkitMatchesSelector;function Na(a,b){if(a&&b)for(var c=Object.getOwnPropertyNames(b),d=0,e=void 0;d<c.length&&(e=c[d]);d++){var f=Object.getOwnPropertyDescriptor(b,e);f&&Object.defineProperty(a,e,f)}}function Oa(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];for(d=0;d<c.length;d++)Na(a,c[d]);return a}function Pa(a,b){for(var c in b)a[c]=b[c]}
var Qa=document.createTextNode(""),Ra=0,Sa=[];(new MutationObserver(function(){for(;Sa.length;)try{Sa.shift()()}catch(a){throw Qa.textContent=Ra++,a;}})).observe(Qa,{characterData:!0});function Ta(a){Sa.push(a);Qa.textContent=Ra++}var Ua=!!document.contains;function Va(a,b){for(;b;){if(b==a)return!0;b=b.parentNode}return!1}
function Wa(a){for(var b=a.length-1;0<=b;b--){var c=a[b],d=c.getAttribute("id")||c.getAttribute("name");d&&"length"!==d&&isNaN(d)&&(a[d]=c)}a.item=function(b){return a[b]};a.namedItem=function(b){if("length"!==b&&isNaN(b)&&a[b])return a[b];for(var c=ba(a),d=c.next();!d.done;d=c.next())if(d=d.value,(d.getAttribute("id")||d.getAttribute("name"))==b)return d;return null};return a};var Xa=[],Ya;function Za(a){Ya||(Ya=!0,Ta($a));Xa.push(a)}function $a(){Ya=!1;for(var a=!!Xa.length;Xa.length;)Xa.shift()();return a}$a.list=Xa;function ab(){this.da=!1;this.addedNodes=[];this.removedNodes=[];this.ha=new Set}function bb(a){a.da||(a.da=!0,Ta(function(){a.flush()}))}ab.prototype.flush=function(){if(this.da){this.da=!1;var a=this.takeRecords();a.length&&this.ha.forEach(function(b){b(a)})}};ab.prototype.takeRecords=function(){if(this.addedNodes.length||this.removedNodes.length){var a=[{addedNodes:this.addedNodes,removedNodes:this.removedNodes}];this.addedNodes=[];this.removedNodes=[];return a}return[]};
function cb(a,b){var c=t(a);c.L||(c.L=new ab);c.L.ha.add(b);var d=c.L;return{zb:b,I:d,Wb:a,takeRecords:function(){return d.takeRecords()}}}function db(a){var b=a&&a.I;b&&(b.ha["delete"](a.zb),b.ha.size||(t(a.Wb).L=null))}
function jb(a,b){var c=b.getRootNode();return a.map(function(a){var b=c===a.target.getRootNode();if(b&&a.addedNodes){if(b=Array.from(a.addedNodes).filter(function(a){return c===a.getRootNode()}),b.length)return a=Object.create(a),Object.defineProperty(a,"addedNodes",{value:b,configurable:!0}),a}else if(b)return a}).filter(function(a){return a})};var kb=Element.prototype.insertBefore,lb=Element.prototype.replaceChild,mb=Element.prototype.removeChild,nb=Element.prototype.setAttribute,ob=Element.prototype.removeAttribute,pb=Element.prototype.cloneNode,qb=Document.prototype.importNode,rb=Element.prototype.addEventListener,sb=Element.prototype.removeEventListener,tb=Window.prototype.addEventListener,ub=Window.prototype.removeEventListener,vb=Element.prototype.dispatchEvent,wb=Node.prototype.contains||HTMLElement.prototype.contains,xb=Document.prototype.getElementById,
yb=Element.prototype.querySelector,zb=DocumentFragment.prototype.querySelector,Ab=Document.prototype.querySelector,Bb=Element.prototype.querySelectorAll,Cb=DocumentFragment.prototype.querySelectorAll,Db=Document.prototype.querySelectorAll,y={};y.appendChild=Element.prototype.appendChild;y.insertBefore=kb;y.replaceChild=lb;y.removeChild=mb;y.setAttribute=nb;y.removeAttribute=ob;y.cloneNode=pb;y.importNode=qb;y.addEventListener=rb;y.removeEventListener=sb;y.Nc=tb;y.Oc=ub;y.dispatchEvent=vb;
y.contains=wb;y.getElementById=xb;y.Uc=yb;y.Xc=zb;y.Sc=Ab;y.querySelector=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return yb.call(this,a);case Node.DOCUMENT_NODE:return Ab.call(this,a);default:return zb.call(this,a)}};y.Vc=Bb;y.Yc=Cb;y.Tc=Db;y.querySelectorAll=function(a){switch(this.nodeType){case Node.ELEMENT_NODE:return Bb.call(this,a);case Node.DOCUMENT_NODE:return Db.call(this,a);default:return Cb.call(this,a)}};var Eb=/[&\u00A0"]/g,Fb=/[&\u00A0<>]/g;function Gb(a){switch(a){case "&":return"&amp;";case "<":return"&lt;";case ">":return"&gt;";case '"':return"&quot;";case "\u00a0":return"&nbsp;"}}function Hb(a){for(var b={},c=0;c<a.length;c++)b[a[c]]=!0;return b}var Ib=Hb("area base br col command embed hr img input keygen link meta param source track wbr".split(" ")),Jb=Hb("style script xmp iframe noembed noframes plaintext noscript".split(" "));
function Kb(a,b){"template"===a.localName&&(a=a.content);for(var c="",d=b?b(a):a.childNodes,e=0,f=d.length,g=void 0;e<f&&(g=d[e]);e++){a:{var h=g;var k=a,l=b;switch(h.nodeType){case Node.ELEMENT_NODE:k=h.localName;for(var n="<"+k,q=h.attributes,v=0,S;S=q[v];v++)n+=" "+S.name+'="'+S.value.replace(Eb,Gb)+'"';n+=">";h=Ib[k]?n:n+Kb(h,l)+"</"+k+">";break a;case Node.TEXT_NODE:h=h.data;h=k&&Jb[k.localName]?h:h.replace(Fb,Gb);break a;case Node.COMMENT_NODE:h="\x3c!--"+h.data+"--\x3e";break a;default:throw window.console.error(h),
Error("not implemented");}}c+=h}return c};var z=document.createTreeWalker(document,NodeFilter.SHOW_ALL,null,!1),A=document.createTreeWalker(document,NodeFilter.SHOW_ELEMENT,null,!1);function Lb(a){var b=[];z.currentNode=a;for(a=z.firstChild();a;)b.push(a),a=z.nextSibling();return b}
var B={parentNode:function(a){z.currentNode=a;return z.parentNode()},firstChild:function(a){z.currentNode=a;return z.firstChild()},lastChild:function(a){z.currentNode=a;return z.lastChild()},previousSibling:function(a){z.currentNode=a;return z.previousSibling()},nextSibling:function(a){z.currentNode=a;return z.nextSibling()}};B.childNodes=Lb;B.parentElement=function(a){A.currentNode=a;return A.parentNode()};B.firstElementChild=function(a){A.currentNode=a;return A.firstChild()};
B.lastElementChild=function(a){A.currentNode=a;return A.lastChild()};B.previousElementSibling=function(a){A.currentNode=a;return A.previousSibling()};B.nextElementSibling=function(a){A.currentNode=a;return A.nextSibling()};B.children=function(a){var b=[];A.currentNode=a;for(a=A.firstChild();a;)b.push(a),a=A.nextSibling();return Wa(b)};B.innerHTML=function(a){return Kb(a,function(a){return Lb(a)})};
B.textContent=function(a){switch(a.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:a=document.createTreeWalker(a,NodeFilter.SHOW_TEXT,null,!1);for(var b="",c;c=a.nextNode();)b+=c.nodeValue;return b;default:return a.nodeValue}};var Mb=w.v,Nb=[Node.prototype,Element.prototype,HTMLElement.prototype];function C(a){var b;a:{for(b=0;b<Nb.length;b++){var c=Nb[b];if(c.hasOwnProperty(a)){b=c;break a}}b=void 0}if(!b)throw Error("Could not find descriptor for "+a);return Object.getOwnPropertyDescriptor(b,a)}
var E=Mb?{parentNode:C("parentNode"),firstChild:C("firstChild"),lastChild:C("lastChild"),previousSibling:C("previousSibling"),nextSibling:C("nextSibling"),childNodes:C("childNodes"),parentElement:C("parentElement"),previousElementSibling:C("previousElementSibling"),nextElementSibling:C("nextElementSibling"),innerHTML:C("innerHTML"),textContent:C("textContent"),firstElementChild:C("firstElementChild"),lastElementChild:C("lastElementChild"),children:C("children")}:{},Ob=Mb?{firstElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,
"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(DocumentFragment.prototype,"children")}:{},Pb=Mb?{firstElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"firstElementChild"),lastElementChild:Object.getOwnPropertyDescriptor(Document.prototype,"lastElementChild"),children:Object.getOwnPropertyDescriptor(Document.prototype,"children")}:{},Qb={ib:E,Wc:Ob,Rc:Pb,parentNode:function(a){return E.parentNode.get.call(a)},
firstChild:function(a){return E.firstChild.get.call(a)},lastChild:function(a){return E.lastChild.get.call(a)},previousSibling:function(a){return E.previousSibling.get.call(a)},nextSibling:function(a){return E.nextSibling.get.call(a)},childNodes:function(a){return Array.prototype.slice.call(E.childNodes.get.call(a))},parentElement:function(a){return E.parentElement.get.call(a)},previousElementSibling:function(a){return E.previousElementSibling.get.call(a)},nextElementSibling:function(a){return E.nextElementSibling.get.call(a)},
innerHTML:function(a){return E.innerHTML.get.call(a)},textContent:function(a){return E.textContent.get.call(a)},children:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Ob.children.get.call(a);case Node.DOCUMENT_NODE:return Pb.children.get.call(a);default:return E.children.get.call(a)}},firstElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Ob.firstElementChild.get.call(a);case Node.DOCUMENT_NODE:return Pb.firstElementChild.get.call(a);default:return E.firstElementChild.get.call(a)}},
lastElementChild:function(a){switch(a.nodeType){case Node.DOCUMENT_FRAGMENT_NODE:return Ob.lastElementChild.get.call(a);case Node.DOCUMENT_NODE:return Pb.lastElementChild.get.call(a);default:return E.lastElementChild.get.call(a)}}};var F=w.ob?Qb:B;function Rb(a){for(;a.firstChild;)a.removeChild(a.firstChild)}
var Sb=w.v,Tb=document.implementation.createHTMLDocument("inert"),Ub=Object.getOwnPropertyDescriptor(Node.prototype,"isConnected"),Vb=Ub&&Ub.get,Wb=Object.getOwnPropertyDescriptor(Document.prototype,"activeElement"),Xb={parentElement:{get:function(){var a=u(this);(a=a&&a.parentNode)&&a.nodeType!==Node.ELEMENT_NODE&&(a=null);return void 0!==a?a:F.parentElement(this)},configurable:!0},parentNode:{get:function(){var a=u(this);a=a&&a.parentNode;return void 0!==a?a:F.parentNode(this)},configurable:!0},
nextSibling:{get:function(){var a=u(this);a=a&&a.nextSibling;return void 0!==a?a:F.nextSibling(this)},configurable:!0},previousSibling:{get:function(){var a=u(this);a=a&&a.previousSibling;return void 0!==a?a:F.previousSibling(this)},configurable:!0},nextElementSibling:{get:function(){var a=u(this);if(a&&void 0!==a.nextSibling){for(a=this.nextSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return F.nextElementSibling(this)},configurable:!0},previousElementSibling:{get:function(){var a=
u(this);if(a&&void 0!==a.previousSibling){for(a=this.previousSibling;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return F.previousElementSibling(this)},configurable:!0}},Yb={className:{get:function(){return this.getAttribute("class")||""},set:function(a){this.setAttribute("class",a)},configurable:!0}},Zb={childNodes:{get:function(){if(Ja(this)){var a=u(this);if(!a.childNodes){a.childNodes=[];for(var b=this.firstChild;b;b=b.nextSibling)a.childNodes.push(b)}var c=a.childNodes}else c=
F.childNodes(this);c.item=function(a){return c[a]};return c},configurable:!0},childElementCount:{get:function(){return this.children.length},configurable:!0},firstChild:{get:function(){var a=u(this);a=a&&a.firstChild;return void 0!==a?a:F.firstChild(this)},configurable:!0},lastChild:{get:function(){var a=u(this);a=a&&a.lastChild;return void 0!==a?a:F.lastChild(this)},configurable:!0},textContent:{get:function(){if(Ja(this)){for(var a=[],b=0,c=this.childNodes,d;d=c[b];b++)d.nodeType!==Node.COMMENT_NODE&&
a.push(d.textContent);return a.join("")}return F.textContent(this)},set:function(a){if("undefined"===typeof a||null===a)a="";switch(this.nodeType){case Node.ELEMENT_NODE:case Node.DOCUMENT_FRAGMENT_NODE:if(!Ja(this)&&Sb){var b=this.firstChild;(b!=this.lastChild||b&&b.nodeType!=Node.TEXT_NODE)&&Rb(this);Qb.ib.textContent.set.call(this,a)}else Rb(this),(0<a.length||this.nodeType===Node.ELEMENT_NODE)&&this.appendChild(document.createTextNode(a));break;default:this.nodeValue=a}},configurable:!0},firstElementChild:{get:function(){var a=
u(this);if(a&&void 0!==a.firstChild){for(a=this.firstChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.nextSibling;return a}return F.firstElementChild(this)},configurable:!0},lastElementChild:{get:function(){var a=u(this);if(a&&void 0!==a.lastChild){for(a=this.lastChild;a&&a.nodeType!==Node.ELEMENT_NODE;)a=a.previousSibling;return a}return F.lastElementChild(this)},configurable:!0},children:{get:function(){return Ja(this)?Wa(Array.prototype.filter.call(this.childNodes,function(a){return a.nodeType===Node.ELEMENT_NODE})):
F.children(this)},configurable:!0},innerHTML:{get:function(){return Ja(this)?Kb("template"===this.localName?this.content:this):F.innerHTML(this)},set:function(a){var b="template"===this.localName?this.content:this;Rb(b);var c=this.localName||"div";c=this.namespaceURI&&this.namespaceURI!==Tb.namespaceURI?Tb.createElementNS(this.namespaceURI,c):Tb.createElement(c);Sb?Qb.ib.innerHTML.set.call(c,a):c.innerHTML=a;for(a="template"===this.localName?c.content:c;a.firstChild;)b.appendChild(a.firstChild)},
configurable:!0}},$b={shadowRoot:{get:function(){var a=u(this);return a&&a.kb||null},configurable:!0}},ac={activeElement:{get:function(){var a=Wb&&Wb.get?Wb.get.call(document):w.v?void 0:document.activeElement;if(a&&a.nodeType){var b=!!x(this);if(this===document||b&&this.host!==a&&y.contains.call(this.host,a)){for(b=Ka(a);b&&b!==this;)a=b.host,b=Ka(a);a=this===document?b?null:a:b===this?a:null}else a=null}else a=null;return a},set:function(){},configurable:!0}};
function G(a,b,c){for(var d in b){var e=Object.getOwnPropertyDescriptor(a,d);e&&e.configurable||!e&&c?Object.defineProperty(a,d,b[d]):c&&console.warn("Could not define",d,"on",a)}}function bc(a){G(a,Xb);G(a,Yb);G(a,Zb);G(a,ac)}
function cc(){var a=H.prototype;a.__proto__=DocumentFragment.prototype;G(a,Xb,!0);G(a,Zb,!0);G(a,ac,!0);Object.defineProperties(a,{nodeType:{value:Node.DOCUMENT_FRAGMENT_NODE,configurable:!0},nodeName:{value:"#document-fragment",configurable:!0},nodeValue:{value:null,configurable:!0}});["localName","namespaceURI","prefix"].forEach(function(b){Object.defineProperty(a,b,{value:void 0,configurable:!0})});["ownerDocument","baseURI","isConnected"].forEach(function(b){Object.defineProperty(a,b,{get:function(){return this.host[b]},
configurable:!0})})}var dc=w.v?function(){}:function(a){var b=t(a);b.Ka||(b.Ka=!0,G(a,Xb,!0),G(a,Yb,!0))},ec=w.v?function(){}:function(a){t(a).rb||(G(a,Zb,!0),G(a,$b,!0))};var fc=F.childNodes;function gc(a,b,c){ec(b);var d=t(b);void 0!==d.firstChild&&(d.childNodes=null);if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){d=a.childNodes;for(var e=0;e<d.length;e++)hc(d[e],b,c);a=t(a);b=void 0!==a.firstChild?null:void 0;a.firstChild=a.lastChild=b;a.childNodes=b}else hc(a,b,c)}
function hc(a,b,c){dc(a);c=c||null;var d=t(a),e=t(b),f=c?t(c):null;d.previousSibling=c?f.previousSibling:b.lastChild;if(f=u(d.previousSibling))f.nextSibling=a;if(f=u(d.nextSibling=c))f.previousSibling=a;d.parentNode=b;c?c===e.firstChild&&(e.firstChild=a):(e.lastChild=a,e.firstChild||(e.firstChild=a));e.childNodes=null}
function ic(a,b){var c=t(a);b=t(b);a===b.firstChild&&(b.firstChild=c.nextSibling);a===b.lastChild&&(b.lastChild=c.previousSibling);a=c.previousSibling;var d=c.nextSibling;a&&(t(a).nextSibling=d);d&&(t(d).previousSibling=a);c.parentNode=c.previousSibling=c.nextSibling=void 0;void 0!==b.childNodes&&(b.childNodes=null)}
function jc(a,b){var c=t(a);if(void 0===c.firstChild)for(c.childNodes=null,b=b||fc(a),c.firstChild=b[0]||null,c.lastChild=b[b.length-1]||null,ec(a),c=0;c<b.length;c++){var d=b[c],e=t(d);e.parentNode=a;e.nextSibling=b[c+1]||null;e.previousSibling=b[c-1]||null;dc(d)}};var kc=F.parentNode,lc=window.document,mc=w.$c;
function nc(a,b,c){if(a.ownerDocument!==lc&&b.ownerDocument!==lc)return y.insertBefore.call(a,b,c);if(b===a)throw Error("Failed to execute 'appendChild' on 'Node': The new child element contains the parent.");if(c){var d=u(c);d=d&&d.parentNode;if(void 0!==d&&d!==a||void 0===d&&kc(c)!==a)throw Error("Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node.");}if(c===b)return b;var e=[],f=oc,g=Ka(a);var h=g?g.host.localName:pc(a);
if(b.parentNode){var k=pc(b);qc(b.parentNode,b,!!g||!(b.getRootNode()instanceof ShadowRoot));f=function(a,b){I()&&(wc(a,k),oc(a,b))}}d=!0;var l=(!mc||void 0===b.__noInsertionPoint)&&!xc(b,h);if(g)b.__noInsertionPoint&&!l||yc(b,function(a){"slot"===a.localName&&e.push(a);l&&f(a,h)});else if(l){var n=pc(b);yc(b,function(a){I()&&(wc(a,n),oc(a,h))})}e.length&&g.wb(e);("slot"===a.localName||e.length)&&g&&g.B();Ja(a)&&(gc(b,a,c),g=u(a),zc(a)?(g.root.B(),d=!1):g.root&&(d=!1));d?(d=x(a)?a.host:a,c?(c=Ac(c),
y.insertBefore.call(d,b,c)):y.appendChild.call(d,b)):b.ownerDocument!==a.ownerDocument&&a.ownerDocument.adoptNode(b);Bc(a,b);return b}
function qc(a,b,c){c=void 0===c?!1:c;if(a.ownerDocument!==lc)return y.removeChild.call(a,b);if(b.parentNode!==a)throw Error("The node to be removed is not a child of this node: "+b);var d=Ka(b),e=u(a);if(Ja(a)&&(ic(b,a),zc(a))){e.root.B();var f=!0}if(I()&&!c&&d){var g=pc(b);yc(b,function(a){wc(a,g)})}Cc(b);if(d){var h=a&&"slot"===a.localName;h&&(f=!0);((c=d.$b(b))||h)&&d.B()}f||(f=x(a)?a.host:a,(!e.root&&"slot"!==b.localName||f===kc(b))&&y.removeChild.call(f,b));Bc(a,null,b);return b}
function Cc(a){var b=u(a);if(b&&void 0!==b.U){b=a.childNodes;for(var c=0,d=b.length,e=void 0;c<d&&(e=b[c]);c++)Cc(e)}if(a=u(a))a.U=void 0}function Ac(a){var b=a;a&&"slot"===a.localName&&(b=(b=(b=u(a))&&b.G)&&b.length?b[0]:Ac(a.nextSibling));return b}function zc(a){return(a=(a=u(a))&&a.root)&&a.Sa()}function Dc(a,b){"slot"===b?(a=a.parentNode,zc(a)&&u(a).root.B()):"slot"===a.localName&&"name"===b&&(b=Ka(a))&&(b.mc(a),b.B())}
function Bc(a,b,c){if(a=(a=u(a))&&a.L)b&&a.addedNodes.push(b),c&&a.removedNodes.push(c),bb(a)}function Ec(a){if(a&&a.nodeType){var b=t(a),c=b.U;void 0===c&&(x(a)?(c=a,b.U=c):(c=(c=a.parentNode)?Ec(c):a,y.contains.call(document.documentElement,a)&&(b.U=c)));return c}}function Fc(a,b,c){var d=[];Gc(a.childNodes,b,c,d);return d}
function Gc(a,b,c,d){for(var e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++){var h;if(h=g.nodeType===Node.ELEMENT_NODE){h=g;var k=b,l=c,n=d,q=k(h);q&&n.push(h);l&&l(q)?h=q:(Gc(h.childNodes,k,l,n),h=void 0)}if(h)break}}function Hc(a){a=a.getRootNode();x(a)&&a.Xa()}var Ic=null;function I(){Ic||(Ic=window.ShadyCSS&&window.ShadyCSS.ScopingShim);return Ic||null}
function Jc(a,b,c){if(a.ownerDocument!==lc)y.setAttribute.call(a,b,c);else{var d=I();d&&"class"===b?d.setElementClass(a,c):(y.setAttribute.call(a,b,c),Dc(a,b))}}function Kc(a,b){if(a.ownerDocument!==document||"template"===a.localName)return y.importNode.call(document,a,b);var c=y.importNode.call(document,a,!1);if(b){a=a.childNodes;b=0;for(var d;b<a.length;b++)d=Kc(a[b],!0),c.appendChild(d)}return c}function oc(a,b){var c=I();c&&c.scopeNode(a,b)}function wc(a,b){var c=I();c&&c.unscopeNode(a,b)}
function xc(a,b){var c=I();if(!c)return!0;if(a.nodeType===Node.DOCUMENT_FRAGMENT_NODE){c=!0;for(var d=0;c&&d<a.childNodes.length;d++)c=c&&xc(a.childNodes[d],b);return c}return a.nodeType!==Node.ELEMENT_NODE?!0:c.currentScopeForNode(a)===b}function pc(a){if(a.nodeType!==Node.ELEMENT_NODE)return"";var b=I();return b?b.currentScopeForNode(a):""}
function yc(a,b){if(a){a.nodeType===Node.ELEMENT_NODE&&b(a);for(var c=0,d;c<a.childNodes.length;c++)d=a.childNodes[c],d.nodeType===Node.ELEMENT_NODE&&yc(d,b)}};var Lc="__eventWrappers"+Date.now(),Mc=function(){var a=Object.getOwnPropertyDescriptor(Event.prototype,"composed");return a?function(b){return a.get.call(b)}:null}(),Nc={blur:!0,focus:!0,focusin:!0,focusout:!0,click:!0,dblclick:!0,mousedown:!0,mouseenter:!0,mouseleave:!0,mousemove:!0,mouseout:!0,mouseover:!0,mouseup:!0,wheel:!0,beforeinput:!0,input:!0,keydown:!0,keyup:!0,compositionstart:!0,compositionupdate:!0,compositionend:!0,touchstart:!0,touchend:!0,touchmove:!0,touchcancel:!0,pointerover:!0,
pointerenter:!0,pointerdown:!0,pointermove:!0,pointerup:!0,pointercancel:!0,pointerout:!0,pointerleave:!0,gotpointercapture:!0,lostpointercapture:!0,dragstart:!0,drag:!0,dragenter:!0,dragleave:!0,dragover:!0,drop:!0,dragend:!0,DOMActivate:!0,DOMFocusIn:!0,DOMFocusOut:!0,keypress:!0},Oc={DOMAttrModified:!0,DOMAttributeNameChanged:!0,DOMCharacterDataModified:!0,DOMElementNameChanged:!0,DOMNodeInserted:!0,DOMNodeInsertedIntoDocument:!0,DOMNodeRemoved:!0,DOMNodeRemovedFromDocument:!0,DOMSubtreeModified:!0};
function Pc(a,b){var c=[],d=a;for(a=a===window?window:a.getRootNode();d;)c.push(d),d=d.assignedSlot?d.assignedSlot:d.nodeType===Node.DOCUMENT_FRAGMENT_NODE&&d.host&&(b||d!==a)?d.host:d.parentNode;c[c.length-1]===document&&c.push(window);return c}function Qc(a,b){if(!x)return a;a=Pc(a,!0);for(var c=0,d,e=void 0,f,g=void 0;c<b.length;c++)if(d=b[c],f=d===window?window:d.getRootNode(),f!==e&&(g=a.indexOf(f),e=f),!x(f)||-1<g)return d}
var Rc={get composed(){void 0===this.Y&&(Mc?this.Y="focusin"===this.type||"focusout"===this.type||Mc(this):!1!==this.isTrusted&&(this.Y=Nc[this.type]));return this.Y||!1},composedPath:function(){this.Ja||(this.Ja=Pc(this.__target,this.composed));return this.Ja},get target(){return Qc(this.currentTarget||this.__previousCurrentTarget,this.composedPath())},get relatedTarget(){if(!this.ma)return null;this.La||(this.La=Pc(this.ma,!0));return Qc(this.currentTarget||this.__previousCurrentTarget,this.La)},
stopPropagation:function(){Event.prototype.stopPropagation.call(this);this.la=!0},stopImmediatePropagation:function(){Event.prototype.stopImmediatePropagation.call(this);this.la=this.qb=!0}};function Sc(a){function b(b,d){b=new a(b,d);b.Y=d&&!!d.composed;return b}Pa(b,a);b.prototype=a.prototype;return b}var Tc={focus:!0,blur:!0};function Uc(a){return a.__target!==a.target||a.ma!==a.relatedTarget}
function Vc(a,b,c){if(c=b.__handlers&&b.__handlers[a.type]&&b.__handlers[a.type][c])for(var d=0,e;(e=c[d])&&(!Uc(a)||a.target!==a.relatedTarget)&&(e.call(b,a),!a.qb);d++);}
function Wc(a){var b=a.composedPath();Object.defineProperty(a,"currentTarget",{get:function(){return d},configurable:!0});for(var c=b.length-1;0<=c;c--){var d=b[c];Vc(a,d,"capture");if(a.la)return}Object.defineProperty(a,"eventPhase",{get:function(){return Event.AT_TARGET}});var e;for(c=0;c<b.length;c++){d=b[c];var f=u(d);f=f&&f.root;if(0===c||f&&f===e)if(Vc(a,d,"bubble"),d!==window&&(e=d.getRootNode()),a.la)break}}
function Xc(a,b,c,d,e,f){for(var g=0;g<a.length;g++){var h=a[g],k=h.type,l=h.capture,n=h.once,q=h.passive;if(b===h.node&&c===k&&d===l&&e===n&&f===q)return g}return-1}
function Yc(a,b,c){if(b){var d=typeof b;if("function"===d||"object"===d)if("object"!==d||b.handleEvent&&"function"===typeof b.handleEvent){var e=this instanceof Window?y.Nc:y.addEventListener;if(Oc[a])return e.call(this,a,b,c);if(c&&"object"===typeof c){var f=!!c.capture;var g=!!c.once;var h=!!c.passive}else f=!!c,h=g=!1;var k=c&&c.na||this,l=b[Lc];if(l){if(-1<Xc(l,k,a,f,g,h))return}else b[Lc]=[];l=function(e){g&&this.removeEventListener(a,b,c);e.__target||Zc(e);if(k!==this){var f=Object.getOwnPropertyDescriptor(e,
"currentTarget");Object.defineProperty(e,"currentTarget",{get:function(){return k},configurable:!0})}e.__previousCurrentTarget=e.currentTarget;if(!x(k)||-1!=e.composedPath().indexOf(k))if(e.composed||-1<e.composedPath().indexOf(k))if(Uc(e)&&e.target===e.relatedTarget)e.eventPhase===Event.BUBBLING_PHASE&&e.stopImmediatePropagation();else if(e.eventPhase===Event.CAPTURING_PHASE||e.bubbles||e.target===k||k instanceof Window){var h="function"===d?b.call(k,e):b.handleEvent&&b.handleEvent(e);k!==this&&
(f?(Object.defineProperty(e,"currentTarget",f),f=null):delete e.currentTarget);return h}};b[Lc].push({node:k,type:a,capture:f,once:g,passive:h,Pc:l});Tc[a]?(this.__handlers=this.__handlers||{},this.__handlers[a]=this.__handlers[a]||{capture:[],bubble:[]},this.__handlers[a][f?"capture":"bubble"].push(l)):e.call(this,a,l,c)}}}
function $c(a,b,c){if(b){var d=this instanceof Window?y.Oc:y.removeEventListener;if(Oc[a])return d.call(this,a,b,c);if(c&&"object"===typeof c){var e=!!c.capture;var f=!!c.once;var g=!!c.passive}else e=!!c,g=f=!1;var h=c&&c.na||this,k=void 0;var l=null;try{l=b[Lc]}catch(n){}l&&(f=Xc(l,h,a,e,f,g),-1<f&&(k=l.splice(f,1)[0].Pc,l.length||(b[Lc]=void 0)));d.call(this,a,k||b,c);k&&Tc[a]&&this.__handlers&&this.__handlers[a]&&(a=this.__handlers[a][e?"capture":"bubble"],k=a.indexOf(k),-1<k&&a.splice(k,1))}}
function ad(){for(var a in Tc)window.addEventListener(a,function(a){a.__target||(Zc(a),Wc(a))},!0)}function Zc(a){a.__target=a.target;a.ma=a.relatedTarget;if(w.v){var b=Object.getPrototypeOf(a);if(!b.hasOwnProperty("__patchProto")){var c=Object.create(b);c.Qc=b;Na(c,Rc);b.__patchProto=c}a.__proto__=b.__patchProto}else Na(a,Rc)}var bd=Sc(window.Event),cd=Sc(window.CustomEvent),dd=Sc(window.MouseEvent);
function ed(){window.Event=bd;window.CustomEvent=cd;window.MouseEvent=dd;ad();if(!Mc&&Object.getOwnPropertyDescriptor(Event.prototype,"isTrusted")){var a=function(){var a=new MouseEvent("click",{bubbles:!0,cancelable:!0,composed:!0});this.dispatchEvent(a)};Element.prototype.click?Element.prototype.click=a:HTMLElement.prototype.click&&(HTMLElement.prototype.click=a)}};function fd(a,b){return{index:a,V:[],ga:b}}
function gd(a,b,c,d){var e=0,f=0,g=0,h=0,k=Math.min(b-e,d-f);if(0==e&&0==f)a:{for(g=0;g<k;g++)if(a[g]!==c[g])break a;g=k}if(b==a.length&&d==c.length){h=a.length;for(var l=c.length,n=0;n<k-g&&hd(a[--h],c[--l]);)n++;h=n}e+=g;f+=g;b-=h;d-=h;if(0==b-e&&0==d-f)return[];if(e==b){for(b=fd(e,0);f<d;)b.V.push(c[f++]);return[b]}if(f==d)return[fd(e,b-e)];k=e;g=f;d=d-g+1;h=b-k+1;b=Array(d);for(l=0;l<d;l++)b[l]=Array(h),b[l][0]=l;for(l=0;l<h;l++)b[0][l]=l;for(l=1;l<d;l++)for(n=1;n<h;n++)if(a[k+n-1]===c[g+l-1])b[l][n]=
b[l-1][n-1];else{var q=b[l-1][n]+1,v=b[l][n-1]+1;b[l][n]=q<v?q:v}k=b.length-1;g=b[0].length-1;d=b[k][g];for(a=[];0<k||0<g;)0==k?(a.push(2),g--):0==g?(a.push(3),k--):(h=b[k-1][g-1],l=b[k-1][g],n=b[k][g-1],q=l<n?l<h?l:h:n<h?n:h,q==h?(h==d?a.push(0):(a.push(1),d=h),k--,g--):q==l?(a.push(3),k--,d=l):(a.push(2),g--,d=n));a.reverse();b=void 0;k=[];for(g=0;g<a.length;g++)switch(a[g]){case 0:b&&(k.push(b),b=void 0);e++;f++;break;case 1:b||(b=fd(e,0));b.ga++;e++;b.V.push(c[f]);f++;break;case 2:b||(b=fd(e,
0));b.ga++;e++;break;case 3:b||(b=fd(e,0)),b.V.push(c[f]),f++}b&&k.push(b);return k}function hd(a,b){return a===b};var id=F.parentNode,jd=F.childNodes,kd={},ld=w.deferConnectionCallbacks&&"loading"===document.readyState,md;function nd(a){var b=[];do b.unshift(a);while(a=a.parentNode);return b}
function H(a,b,c){if(a!==kd)throw new TypeError("Illegal constructor");this.Sb="ShadyRoot";this.host=b;this.Vb=c&&c.mode;a=jd(b);jc(b,a);c=t(b);c.root=this;c.kb="closed"!==this.Vb?this:null;c=t(this);c.firstChild=c.lastChild=c.parentNode=c.nextSibling=c.previousSibling=null;c.childNodes=[];this.Ta=this.S=!1;this.s=this.b=this.a=null;if(w.preferPerformance){c=0;for(var d=a.length;c<d;c++)y.removeChild.call(b,a[c])}else this.B()}H.prototype.B=function(){var a=this;this.S||(this.S=!0,Za(function(){return a.Xa()}))};
H.prototype.Nb=function(){for(var a,b=this;b;)b.S&&(a=b),b=b.bc();return a};H.prototype.bc=function(){var a=this.host.getRootNode();if(x(a))for(var b=this.host.childNodes,c=0,d;c<b.length;c++)if(d=b[c],this.Ua(d))return a};H.prototype.Xa=function(){var a=this.Nb();a&&a._renderRoot()};
H.prototype._renderRoot=function(){var a=ld;ld=!0;this.S=!1;this.a&&(this.Db(),this.Bb());if(!w.preferPerformance&&!this.Ta)for(var b=this.host.childNodes,c=0,d=b.length;c<d;c++){var e=b[c],f=u(e);id(e)!==this.host||"slot"!==e.localName&&f.assignedSlot||y.removeChild.call(this.host,e)}this.Ta=!0;ld=a;md&&md()};m=H.prototype;
m.Db=function(){this.fa();for(var a=0,b;a<this.a.length;a++)b=this.a[a],this.Ab(b);for(a=this.host.firstChild;a;a=a.nextSibling)this.Pa(a);for(a=0;a<this.a.length;a++){b=this.a[a];var c=u(b);if(!c.assignedNodes.length)for(var d=b.firstChild;d;d=d.nextSibling)this.Pa(d,b);(d=(d=u(b.parentNode))&&d.root)&&(d.Sa()||d.S)&&d._renderRoot();this.Ma(c.G,c.assignedNodes);if(d=c.xa){for(var e=0;e<d.length;e++)u(d[e]).ca=null;c.xa=null;d.length>c.assignedNodes.length&&(c.ia=!0)}c.ia&&(c.ia=!1,this.Qa(b))}};
m.Pa=function(a,b){var c=t(a),d=c.ca;c.ca=null;b||(b=(b=this.b[a.slot||"__catchall"])&&b[0]);b?(t(b).assignedNodes.push(a),c.assignedSlot=b):c.assignedSlot=void 0;d!==c.assignedSlot&&c.assignedSlot&&(t(c.assignedSlot).ia=!0)};m.Ab=function(a){var b=u(a),c=b.assignedNodes;b.assignedNodes=[];b.G=[];if(b.xa=c)for(b=0;b<c.length;b++){var d=u(c[b]);d.ca=d.assignedSlot;d.assignedSlot===a&&(d.assignedSlot=null)}};
m.Ma=function(a,b){for(var c=0,d=void 0;c<b.length&&(d=b[c]);c++)if("slot"==d.localName){var e=u(d).assignedNodes;e&&e.length&&this.Ma(a,e)}else a.push(b[c])};m.Qa=function(a){y.dispatchEvent.call(a,new Event("slotchange"));a=u(a);a.assignedSlot&&this.Qa(a.assignedSlot)};m.Bb=function(){for(var a=this.a,b=[],c=0;c<a.length;c++){var d=a[c].parentNode,e=u(d);e&&e.root||!(0>b.indexOf(d))||b.push(d)}for(a=0;a<b.length;a++)c=b[a],this.lc(c===this?this.host:c,this.Cb(c))};
m.Cb=function(a){var b=[];a=a.childNodes;for(var c=0;c<a.length;c++){var d=a[c];if(this.Ua(d)){d=u(d).G;for(var e=0;e<d.length;e++)b.push(d[e])}else b.push(d)}return b};m.Ua=function(a){return"slot"==a.localName};
m.lc=function(a,b){for(var c=jd(a),d=gd(b,b.length,c,c.length),e=0,f=0,g=void 0;e<d.length&&(g=d[e]);e++){for(var h=0,k=void 0;h<g.V.length&&(k=g.V[h]);h++)id(k)===a&&y.removeChild.call(a,k),c.splice(g.index+f,1);f-=g.ga}e=0;for(f=void 0;e<d.length&&(f=d[e]);e++)for(g=c[f.index],h=f.index;h<f.index+f.ga;h++)k=b[h],y.insertBefore.call(a,k,g),c.splice(h,0,k)};m.Ib=function(){this.s=this.s||[];this.a=this.a||[];this.b=this.b||{}};
m.wb=function(a){this.Ib();this.s.push.apply(this.s,a instanceof Array?a:ca(ba(a)))};m.fa=function(){this.s&&this.s.length&&(this.Tb(this.s),this.s=[])};m.Tb=function(a){for(var b,c=0;c<a.length;c++){var d=a[c];jc(d);jc(d.parentNode);var e=this.Va(d);this.b[e]?(b=b||{},b[e]=!0,this.b[e].push(d)):this.b[e]=[d];this.a.push(d)}if(b)for(var f in b)this.b[f]=this.Za(this.b[f])};m.Va=function(a){var b=a.name||a.getAttribute("name")||"__catchall";return a.ub=b};
m.Za=function(a){return a.sort(function(a,c){a=nd(a);for(var b=nd(c),e=0;e<a.length;e++){c=a[e];var f=b[e];if(c!==f)return a=Array.from(c.parentNode.childNodes),a.indexOf(c)-a.indexOf(f)}})};m.$b=function(a){if(this.a){this.fa();var b=this.b,c;for(c in b)for(var d=b[c],e=0;e<d.length;e++){var f=d[e];if(Va(a,f)){d.splice(e,1);var g=this.a.indexOf(f);0<=g&&this.a.splice(g,1);e--;this.ac(f);g=!0}}return g}};
m.mc=function(a){if(this.a){this.fa();var b=a.ub,c=this.Va(a);if(c!==b){b=this.b[b];var d=b.indexOf(a);0<=d&&b.splice(d,1);b=this.b[c]||(this.b[c]=[]);b.push(a);1<b.length&&(this.b[c]=this.Za(b))}}};m.ac=function(a){a=u(a);var b=a.G;if(b)for(var c=0;c<b.length;c++){var d=b[c],e=id(d);e&&y.removeChild.call(e,d)}a.G=[];a.assignedNodes=[]};m.Sa=function(){this.fa();return!(!this.a||!this.a.length)};
if(window.customElements&&w.Da&&!w.preferPerformance){var od=new Map;md=function(){var a=Array.from(od);od.clear();a=ba(a);for(var b=a.next();!b.done;b=a.next()){b=ba(b.value);var c=b.next().value;b.next().value?c.sb():c.tb()}};ld&&document.addEventListener("readystatechange",function(){ld=!1;md()},{once:!0});var pd=function(a,b,c){var d=0,e="__isConnected"+d++;if(b||c)a.prototype.connectedCallback=a.prototype.sb=function(){ld?od.set(this,!0):this[e]||(this[e]=!0,b&&b.call(this))},a.prototype.disconnectedCallback=
a.prototype.tb=function(){ld?this.isConnected||od.set(this,!1):this[e]&&(this[e]=!1,c&&c.call(this))};return a},qd=window.customElements.define;Object.defineProperty(window.CustomElementRegistry.prototype,"define",{value:function(a,b){var c=b.prototype.connectedCallback,d=b.prototype.disconnectedCallback;qd.call(window.customElements,a,pd(b,c,d));b.prototype.connectedCallback=c;b.prototype.disconnectedCallback=d}})};function rd(a){Hc(a);return(a=u(a))&&a.assignedSlot||null}
var sd={addEventListener:Yc.bind(window),removeEventListener:$c.bind(window)},td={addEventListener:Yc,removeEventListener:$c,appendChild:function(a){return nc(this,a)},insertBefore:function(a,b){return nc(this,a,b)},removeChild:function(a){return qc(this,a)},replaceChild:function(a,b){nc(this,a,b);qc(this,b);return a},cloneNode:function(a){if("template"==this.localName)var b=y.cloneNode.call(this,a);else if(b=y.cloneNode.call(this,!1),a&&b.nodeType!==Node.ATTRIBUTE_NODE){a=this.childNodes;for(var c=
0,d;c<a.length;c++)d=a[c].cloneNode(!0),b.appendChild(d)}return b},getRootNode:function(){return Ec(this)},contains:function(a){return Va(this,a)},dispatchEvent:function(a){$a();return y.dispatchEvent.call(this,a)}};
Object.defineProperties(td,{isConnected:{get:function(){if(Vb&&Vb.call(this))return!0;if(this.nodeType==Node.DOCUMENT_FRAGMENT_NODE)return!1;var a=this.ownerDocument;if(Ua){if(y.contains.call(a,this))return!0}else if(a.documentElement&&y.contains.call(a.documentElement,this))return!0;for(a=this;a&&!(a instanceof Document);)a=a.parentNode||(x(a)?a.host:void 0);return!!(a&&a instanceof Document)},configurable:!0}});
var ud={get assignedSlot(){return rd(this)}},vd={querySelector:function(a){return Fc(this,function(b){return Ma.call(b,a)},function(a){return!!a})[0]||null},querySelectorAll:function(a,b){if(b){b=Array.prototype.slice.call(y.querySelectorAll.call(this,a));var c=this.getRootNode();return b.filter(function(a){return a.getRootNode()==c})}return Fc(this,function(b){return Ma.call(b,a)})}},wd={},xd={assignedNodes:function(a){if("slot"===this.localName){Hc(this);var b=u(this);return b?(a&&a.flatten?b.G:
b.assignedNodes)||[]:[]}}},yd=Oa({setAttribute:function(a,b){Jc(this,a,b)},removeAttribute:function(a){y.removeAttribute.call(this,a);Dc(this,a)},attachShadow:function(a){if(!this)throw"Must provide a host.";if(!a)throw"Not enough arguments.";return new H(kd,this,a)},get slot(){return this.getAttribute("slot")},set slot(a){Jc(this,"slot",a)},get assignedSlot(){return rd(this)}},vd,xd);Object.defineProperties(yd,$b);
var zd={importNode:function(a,b){return Kc(a,b)},getElementById:function(a){return Fc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}};Object.defineProperties(zd,{_activeElement:ac.activeElement});
for(var Ad=HTMLElement.prototype.blur,Bd={blur:function(){var a=u(this);(a=(a=a&&a.root)&&a.activeElement)?a.blur():Ad.call(this)}},Cd={},Dd=ba(Object.getOwnPropertyNames(Document.prototype)),Ed=Dd.next();!Ed.done;Cd={l:Cd.l},Ed=Dd.next())Cd.l=Ed.value,"on"===Cd.l.substring(0,2)&&Object.defineProperty(Bd,Cd.l,{set:function(a){return function(b){var c=t(this),d=a.l.substring(2);c.Z[a.l]&&this.removeEventListener(d,c.Z[a.l]);this.addEventListener(d,b,{});c.Z[a.l]=b}}(Cd),get:function(a){return function(){var b=
u(this);return b&&b.Z[a.l]}}(Cd),configurable:!0});var Fd=Oa({addEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.na=this;this.host.addEventListener(a,b,c)},removeEventListener:function(a,b,c){"object"!==typeof c&&(c={capture:!!c});c.na=this;this.host.removeEventListener(a,b,c)},getElementById:function(a){return Fc(this,function(b){return b.id==a},function(a){return!!a})[0]||null}},vd);w.preferPerformance||(Oa(zd,vd),Oa(wd,vd));
function J(a,b){for(var c=Object.getOwnPropertyNames(b),d=0;d<c.length;d++){var e=c[d],f=Object.getOwnPropertyDescriptor(b,e);f.value?a[e]=f.value:Object.defineProperty(a,e,f)}};if(w.Da){var ShadyDOM={inUse:w.Da,patch:function(a){ec(a);dc(a);return a},isShadyRoot:x,enqueue:Za,flush:$a,settings:w,filterMutations:jb,observeChildren:cb,unobserveChildren:db,nativeMethods:y,nativeTree:F,deferConnectionCallbacks:w.deferConnectionCallbacks,preferPerformance:w.preferPerformance,handlesDynamicScoping:!0};window.ShadyDOM=ShadyDOM;ed();var Gd=window.customElements&&window.customElements.nativeHTMLElement||HTMLElement;J(H.prototype,Fd);J(window.Node.prototype,td);J(window.Window.prototype,
sd);J(window.Text.prototype,ud);J(window.Element.prototype,yd);J(window.DocumentFragment.prototype,wd);J(window.Document.prototype,zd);window.HTMLSlotElement&&J(window.HTMLSlotElement.prototype,xd);J(Gd.prototype,Bd);w.v&&(bc(window.Node.prototype),bc(window.Text.prototype),bc(window.DocumentFragment.prototype),bc(window.Element.prototype),bc(Gd.prototype),bc(window.Document.prototype),window.HTMLSlotElement&&bc(window.HTMLSlotElement.prototype));cc();window.ShadowRoot=H};var Hd=new Set("annotation-xml color-profile font-face font-face-src font-face-uri font-face-format font-face-name missing-glyph".split(" "));function Id(a){var b=Hd.has(a);a=/^[a-z][.0-9_a-z]*-[\-.0-9_a-z]*$/.test(a);return!b&&a}function K(a){var b=a.isConnected;if(void 0!==b)return b;for(;a&&!(a.__CE_isImportDocument||a instanceof Document);)a=a.parentNode||(window.ShadowRoot&&a instanceof ShadowRoot?a.host:void 0);return!(!a||!(a.__CE_isImportDocument||a instanceof Document))}
function Jd(a,b){for(;b&&b!==a&&!b.nextSibling;)b=b.parentNode;return b&&b!==a?b.nextSibling:null}
function Kd(a,b,c){c=void 0===c?new Set:c;for(var d=a;d;){if(d.nodeType===Node.ELEMENT_NODE){var e=d;b(e);var f=e.localName;if("link"===f&&"import"===e.getAttribute("rel")){d=e["import"];if(d instanceof Node&&!c.has(d))for(c.add(d),d=d.firstChild;d;d=d.nextSibling)Kd(d,b,c);d=Jd(a,e);continue}else if("template"===f){d=Jd(a,e);continue}if(e=e.__CE_shadowRoot)for(e=e.firstChild;e;e=e.nextSibling)Kd(e,b,c)}d=d.firstChild?d.firstChild:Jd(a,d)}}function L(a,b,c){a[b]=c};function Ld(){this.o=new Map;this.Oa=new Map;this.va=[];this.ba=!1}function Md(a,b,c){a.o.set(b,c);a.Oa.set(c.constructorFunction,c)}function Nd(a,b){a.ba=!0;a.va.push(b)}function Od(a,b){a.ba&&Kd(b,function(b){return a.N(b)})}Ld.prototype.N=function(a){if(this.ba&&!a.__CE_patched){a.__CE_patched=!0;for(var b=0;b<this.va.length;b++)this.va[b](a)}};function M(a,b){var c=[];Kd(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state?a.connectedCallback(d):Pd(a,d)}}
function N(a,b){var c=[];Kd(b,function(a){return c.push(a)});for(b=0;b<c.length;b++){var d=c[b];1===d.__CE_state&&a.disconnectedCallback(d)}}
function O(a,b,c){c=void 0===c?{}:c;var d=c.Lc||new Set,e=c.upgrade||function(b){return Pd(a,b)},f=[];Kd(b,function(b){if("link"===b.localName&&"import"===b.getAttribute("rel")){var c=b["import"];c instanceof Node&&(c.__CE_isImportDocument=!0,c.__CE_hasRegistry=!0);c&&"complete"===c.readyState?c.__CE_documentLoadHandled=!0:b.addEventListener("load",function(){var c=b["import"];if(!c.__CE_documentLoadHandled){c.__CE_documentLoadHandled=!0;var f=new Set(d);f["delete"](c);O(a,c,{Lc:f,upgrade:e})}})}else f.push(b)},
d);if(a.ba)for(b=0;b<f.length;b++)a.N(f[b]);for(b=0;b<f.length;b++)e(f[b])}
function Pd(a,b){if(void 0===b.__CE_state){var c=b.ownerDocument;if(c.defaultView||c.__CE_isImportDocument&&c.__CE_hasRegistry)if(c=a.o.get(b.localName)){c.constructionStack.push(b);var d=c.constructorFunction;try{try{if(new d!==b)throw Error("The custom element constructor did not produce the element being upgraded.");}finally{c.constructionStack.pop()}}catch(g){throw b.__CE_state=2,g;}b.__CE_state=1;b.__CE_definition=c;if(c.attributeChangedCallback)for(c=c.observedAttributes,d=0;d<c.length;d++){var e=
c[d],f=b.getAttribute(e);null!==f&&a.attributeChangedCallback(b,e,null,f,null)}K(b)&&a.connectedCallback(b)}}}Ld.prototype.connectedCallback=function(a){var b=a.__CE_definition;b.connectedCallback&&b.connectedCallback.call(a)};Ld.prototype.disconnectedCallback=function(a){var b=a.__CE_definition;b.disconnectedCallback&&b.disconnectedCallback.call(a)};
Ld.prototype.attributeChangedCallback=function(a,b,c,d,e){var f=a.__CE_definition;f.attributeChangedCallback&&-1<f.observedAttributes.indexOf(b)&&f.attributeChangedCallback.call(a,b,c,d,e)};function Qd(a){var b=document;this.c=a;this.$=b;this.I=void 0;O(this.c,this.$);"loading"===this.$.readyState&&(this.I=new MutationObserver(this.Pb.bind(this)),this.I.observe(this.$,{childList:!0,subtree:!0}))}Qd.prototype.disconnect=function(){this.I&&this.I.disconnect()};Qd.prototype.Pb=function(a){var b=this.$.readyState;"interactive"!==b&&"complete"!==b||this.disconnect();for(b=0;b<a.length;b++)for(var c=a[b].addedNodes,d=0;d<c.length;d++)O(this.c,c[d])};function Rd(){var a=this;this.ya=this.f=void 0;this.Wa=new Promise(function(b){a.ya=b;a.f&&b(a.f)})}Rd.prototype.resolve=function(a){if(this.f)throw Error("Already resolved.");this.f=a;this.ya&&this.ya(a)};function P(a){this.ra=!1;this.c=a;this.Ba=new Map;this.ta=function(a){return a()};this.aa=!1;this.wa=[];this.Eb=new Qd(a)}m=P.prototype;
m.define=function(a,b){var c=this;if(!(b instanceof Function))throw new TypeError("Custom element constructors must be functions.");if(!Id(a))throw new SyntaxError("The element name '"+a+"' is not valid.");if(this.c.o.get(a))throw Error("A custom element with name '"+a+"' has already been defined.");if(this.ra)throw Error("A custom element is already being defined.");this.ra=!0;try{var d=function(a){var b=e[a];if(void 0!==b&&!(b instanceof Function))throw Error("The '"+a+"' callback must be a function.");
return b},e=b.prototype;if(!(e instanceof Object))throw new TypeError("The custom element constructor's prototype is not an object.");var f=d("connectedCallback");var g=d("disconnectedCallback");var h=d("adoptedCallback");var k=d("attributeChangedCallback");var l=b.observedAttributes||[]}catch(n){return}finally{this.ra=!1}b={localName:a,constructorFunction:b,connectedCallback:f,disconnectedCallback:g,adoptedCallback:h,attributeChangedCallback:k,observedAttributes:l,constructionStack:[]};Md(this.c,
a,b);this.wa.push(b);this.aa||(this.aa=!0,this.ta(function(){return c.Jb()}))};m.upgrade=function(a){O(this.c,a)};
m.Jb=function(){var a=this;if(!1!==this.aa){this.aa=!1;for(var b=this.wa,c=[],d=new Map,e=0;e<b.length;e++)d.set(b[e].localName,[]);O(this.c,document,{upgrade:function(b){if(void 0===b.__CE_state){var e=b.localName,f=d.get(e);f?f.push(b):a.c.o.get(e)&&c.push(b)}}});for(e=0;e<c.length;e++)Pd(this.c,c[e]);for(;0<b.length;){var f=b.shift();e=f.localName;f=d.get(f.localName);for(var g=0;g<f.length;g++)Pd(this.c,f[g]);(e=this.Ba.get(e))&&e.resolve(void 0)}}};m.get=function(a){if(a=this.c.o.get(a))return a.constructorFunction};
m.whenDefined=function(a){if(!Id(a))return Promise.reject(new SyntaxError("'"+a+"' is not a valid custom element name."));var b=this.Ba.get(a);if(b)return b.Wa;b=new Rd;this.Ba.set(a,b);this.c.o.get(a)&&!this.wa.some(function(b){return b.localName===a})&&b.resolve(void 0);return b.Wa};m.Cc=function(a){this.Eb.disconnect();var b=this.ta;this.ta=function(c){return a(function(){return b(c)})}};window.CustomElementRegistry=P;P.prototype.define=P.prototype.define;P.prototype.upgrade=P.prototype.upgrade;
P.prototype.get=P.prototype.get;P.prototype.whenDefined=P.prototype.whenDefined;P.prototype.polyfillWrapFlushCallback=P.prototype.Cc;var Sd=window.Document.prototype.createElement,Td=window.Document.prototype.createElementNS,Ud=window.Document.prototype.importNode,Vd=window.Document.prototype.prepend,Wd=window.Document.prototype.append,Xd=window.DocumentFragment.prototype.prepend,Yd=window.DocumentFragment.prototype.append,Zd=window.Node.prototype.cloneNode,$d=window.Node.prototype.appendChild,ae=window.Node.prototype.insertBefore,be=window.Node.prototype.removeChild,ce=window.Node.prototype.replaceChild,de=Object.getOwnPropertyDescriptor(window.Node.prototype,
"textContent"),ee=window.Element.prototype.attachShadow,fe=Object.getOwnPropertyDescriptor(window.Element.prototype,"innerHTML"),ge=window.Element.prototype.getAttribute,he=window.Element.prototype.setAttribute,ie=window.Element.prototype.removeAttribute,je=window.Element.prototype.getAttributeNS,ke=window.Element.prototype.setAttributeNS,le=window.Element.prototype.removeAttributeNS,me=window.Element.prototype.insertAdjacentElement,ne=window.Element.prototype.insertAdjacentHTML,oe=window.Element.prototype.prepend,
pe=window.Element.prototype.append,qe=window.Element.prototype.before,re=window.Element.prototype.after,se=window.Element.prototype.replaceWith,te=window.Element.prototype.remove,ue=window.HTMLElement,ve=Object.getOwnPropertyDescriptor(window.HTMLElement.prototype,"innerHTML"),we=window.HTMLElement.prototype.insertAdjacentElement,xe=window.HTMLElement.prototype.insertAdjacentHTML;var ye=new function(){};function ze(){var a=Ae;window.HTMLElement=function(){function b(){var b=this.constructor,d=a.Oa.get(b);if(!d)throw Error("The custom element being constructed was not registered with `customElements`.");var e=d.constructionStack;if(0===e.length)return e=Sd.call(document,d.localName),Object.setPrototypeOf(e,b.prototype),e.__CE_state=1,e.__CE_definition=d,a.N(e),e;d=e.length-1;var f=e[d];if(f===ye)throw Error("The HTMLElement constructor was either called reentrantly for this constructor or called multiple times.");
e[d]=ye;Object.setPrototypeOf(f,b.prototype);a.N(f);return f}b.prototype=ue.prototype;Object.defineProperty(b.prototype,"constructor",{writable:!0,configurable:!0,enumerable:!1,value:b});return b}()};function Be(a,b,c){function d(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var f=[],l=0;l<d.length;l++){var n=d[l];n instanceof Element&&K(n)&&f.push(n);if(n instanceof DocumentFragment)for(n=n.firstChild;n;n=n.nextSibling)e.push(n);else e.push(n)}b.apply(this,d);for(d=0;d<f.length;d++)N(a,f[d]);if(K(this))for(d=0;d<e.length;d++)f=e[d],f instanceof Element&&M(a,f)}}void 0!==c.prepend&&(b.prepend=d(c.prepend));void 0!==c.append&&(b.append=d(c.append))}
;function Ce(){var a=Ae;L(Document.prototype,"createElement",function(b){if(this.__CE_hasRegistry){var c=a.o.get(b);if(c)return new c.constructorFunction}b=Sd.call(this,b);a.N(b);return b});L(Document.prototype,"importNode",function(b,c){b=Ud.call(this,b,!!c);this.__CE_hasRegistry?O(a,b):Od(a,b);return b});L(Document.prototype,"createElementNS",function(b,c){if(this.__CE_hasRegistry&&(null===b||"http://www.w3.org/1999/xhtml"===b)){var d=a.o.get(c);if(d)return new d.constructorFunction}b=Td.call(this,
b,c);a.N(b);return b});Be(a,Document.prototype,{prepend:Vd,append:Wd})};function Ie(){function a(a,d){Object.defineProperty(a,"textContent",{enumerable:d.enumerable,configurable:!0,get:d.get,set:function(a){if(this.nodeType===Node.TEXT_NODE)d.set.call(this,a);else{var c=void 0;if(this.firstChild){var e=this.childNodes,h=e.length;if(0<h&&K(this)){c=Array(h);for(var k=0;k<h;k++)c[k]=e[k]}}d.set.call(this,a);if(c)for(a=0;a<c.length;a++)N(b,c[a])}}})}var b=Ae;L(Node.prototype,"insertBefore",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);
a=ae.call(this,a,d);if(K(this))for(d=0;d<c.length;d++)M(b,c[d]);return a}c=K(a);d=ae.call(this,a,d);c&&N(b,a);K(this)&&M(b,a);return d});L(Node.prototype,"appendChild",function(a){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=$d.call(this,a);if(K(this))for(var e=0;e<c.length;e++)M(b,c[e]);return a}c=K(a);e=$d.call(this,a);c&&N(b,a);K(this)&&M(b,a);return e});L(Node.prototype,"cloneNode",function(a){a=Zd.call(this,!!a);this.ownerDocument.__CE_hasRegistry?O(b,a):
Od(b,a);return a});L(Node.prototype,"removeChild",function(a){var c=K(a),e=be.call(this,a);c&&N(b,a);return e});L(Node.prototype,"replaceChild",function(a,d){if(a instanceof DocumentFragment){var c=Array.prototype.slice.apply(a.childNodes);a=ce.call(this,a,d);if(K(this))for(N(b,d),d=0;d<c.length;d++)M(b,c[d]);return a}c=K(a);var f=ce.call(this,a,d),g=K(this);g&&N(b,d);c&&N(b,a);g&&M(b,a);return f});de&&de.get?a(Node.prototype,de):Nd(b,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){for(var a=
[],b=0;b<this.childNodes.length;b++)a.push(this.childNodes[b].textContent);return a.join("")},set:function(a){for(;this.firstChild;)be.call(this,this.firstChild);$d.call(this,document.createTextNode(a))}})})};function Je(a){function b(b){return function(c){for(var d=[],e=0;e<arguments.length;++e)d[e-0]=arguments[e];e=[];for(var h=[],k=0;k<d.length;k++){var l=d[k];l instanceof Element&&K(l)&&h.push(l);if(l instanceof DocumentFragment)for(l=l.firstChild;l;l=l.nextSibling)e.push(l);else e.push(l)}b.apply(this,d);for(d=0;d<h.length;d++)N(a,h[d]);if(K(this))for(d=0;d<e.length;d++)h=e[d],h instanceof Element&&M(a,h)}}var c=Element.prototype;void 0!==qe&&(c.before=b(qe));void 0!==qe&&(c.after=b(re));void 0!==
se&&L(c,"replaceWith",function(b){for(var c=[],d=0;d<arguments.length;++d)c[d-0]=arguments[d];d=[];for(var g=[],h=0;h<c.length;h++){var k=c[h];k instanceof Element&&K(k)&&g.push(k);if(k instanceof DocumentFragment)for(k=k.firstChild;k;k=k.nextSibling)d.push(k);else d.push(k)}h=K(this);se.apply(this,c);for(c=0;c<g.length;c++)N(a,g[c]);if(h)for(N(a,this),c=0;c<d.length;c++)g=d[c],g instanceof Element&&M(a,g)});void 0!==te&&L(c,"remove",function(){var b=K(this);te.call(this);b&&N(a,this)})};function Ke(){function a(a,b){Object.defineProperty(a,"innerHTML",{enumerable:b.enumerable,configurable:!0,get:b.get,set:function(a){var c=this,e=void 0;K(this)&&(e=[],Kd(this,function(a){a!==c&&e.push(a)}));b.set.call(this,a);if(e)for(var f=0;f<e.length;f++){var g=e[f];1===g.__CE_state&&d.disconnectedCallback(g)}this.ownerDocument.__CE_hasRegistry?O(d,this):Od(d,this);return a}})}function b(a,b){L(a,"insertAdjacentElement",function(a,c){var e=K(c);a=b.call(this,a,c);e&&N(d,c);K(a)&&M(d,c);return a})}
function c(a,b){function c(a,b){for(var c=[];a!==b;a=a.nextSibling)c.push(a);for(b=0;b<c.length;b++)O(d,c[b])}L(a,"insertAdjacentHTML",function(a,d){a=a.toLowerCase();if("beforebegin"===a){var e=this.previousSibling;b.call(this,a,d);c(e||this.parentNode.firstChild,this)}else if("afterbegin"===a)e=this.firstChild,b.call(this,a,d),c(this.firstChild,e);else if("beforeend"===a)e=this.lastChild,b.call(this,a,d),c(e||this.firstChild,null);else if("afterend"===a)e=this.nextSibling,b.call(this,a,d),c(this.nextSibling,
e);else throw new SyntaxError("The value provided ("+String(a)+") is not one of 'beforebegin', 'afterbegin', 'beforeend', or 'afterend'.");})}var d=Ae;ee&&L(Element.prototype,"attachShadow",function(a){return this.__CE_shadowRoot=a=ee.call(this,a)});fe&&fe.get?a(Element.prototype,fe):ve&&ve.get?a(HTMLElement.prototype,ve):Nd(d,function(b){a(b,{enumerable:!0,configurable:!0,get:function(){return Zd.call(this,!0).innerHTML},set:function(a){var b="template"===this.localName,c=b?this.content:this,d=Td.call(document,
this.namespaceURI,this.localName);for(d.innerHTML=a;0<c.childNodes.length;)be.call(c,c.childNodes[0]);for(a=b?d.content:d;0<a.childNodes.length;)$d.call(c,a.childNodes[0])}})});L(Element.prototype,"setAttribute",function(a,b){if(1!==this.__CE_state)return he.call(this,a,b);var c=ge.call(this,a);he.call(this,a,b);b=ge.call(this,a);d.attributeChangedCallback(this,a,c,b,null)});L(Element.prototype,"setAttributeNS",function(a,b,c){if(1!==this.__CE_state)return ke.call(this,a,b,c);var e=je.call(this,a,
b);ke.call(this,a,b,c);c=je.call(this,a,b);d.attributeChangedCallback(this,b,e,c,a)});L(Element.prototype,"removeAttribute",function(a){if(1!==this.__CE_state)return ie.call(this,a);var b=ge.call(this,a);ie.call(this,a);null!==b&&d.attributeChangedCallback(this,a,b,null,null)});L(Element.prototype,"removeAttributeNS",function(a,b){if(1!==this.__CE_state)return le.call(this,a,b);var c=je.call(this,a,b);le.call(this,a,b);var e=je.call(this,a,b);c!==e&&d.attributeChangedCallback(this,b,c,e,a)});we?b(HTMLElement.prototype,
we):me?b(Element.prototype,me):console.warn("Custom Elements: `Element#insertAdjacentElement` was not patched.");xe?c(HTMLElement.prototype,xe):ne?c(Element.prototype,ne):console.warn("Custom Elements: `Element#insertAdjacentHTML` was not patched.");Be(d,Element.prototype,{prepend:oe,append:pe});Je(d)};var Le=window.customElements;if(!Le||Le.forcePolyfill||"function"!=typeof Le.define||"function"!=typeof Le.get){var Ae=new Ld;ze();Ce();Be(Ae,DocumentFragment.prototype,{prepend:Xd,append:Yd});Ie();Ke();document.__CE_hasRegistry=!0;var customElements=new P(Ae);Object.defineProperty(window,"customElements",{configurable:!0,enumerable:!0,value:customElements})};function Me(){this.end=this.start=0;this.rules=this.parent=this.previous=null;this.cssText=this.parsedCssText="";this.atRule=!1;this.type=0;this.parsedSelector=this.selector=this.keyframesName=""}
function Ne(a){a=a.replace(Oe,"").replace(Pe,"");var b=Qe,c=a,d=new Me;d.start=0;d.end=c.length;for(var e=d,f=0,g=c.length;f<g;f++)if("{"===c[f]){e.rules||(e.rules=[]);var h=e,k=h.rules[h.rules.length-1]||null;e=new Me;e.start=f+1;e.parent=h;e.previous=k;h.rules.push(e)}else"}"===c[f]&&(e.end=f+1,e=e.parent||d);return b(d,a)}
function Qe(a,b){var c=b.substring(a.start,a.end-1);a.parsedCssText=a.cssText=c.trim();a.parent&&(c=b.substring(a.previous?a.previous.end:a.parent.start,a.start-1),c=_expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(c),c=c.replace(Re," "),c=c.substring(c.lastIndexOf(";")+1),c=a.parsedSelector=a.selector=c.trim(),a.atRule=0===c.indexOf("@"),a.atRule?0===c.indexOf("@media")?a.type=4:c.match(Se)&&(a.type=7,a.keyframesName=a.selector.split(Re).pop()):a.type=0===c.indexOf("--")?
1E3:1);if(c=a.rules)for(var d=0,e=c.length,f=void 0;d<e&&(f=c[d]);d++)Qe(f,b);return a}function _expandUnicodeEscapes$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){return a.replace(/\\([0-9a-f]{1,6})\s/gi,function(a,c){a=c;for(c=6-a.length;c--;)a="0"+a;return"\\"+a})}
function Te(a,b,c){c=void 0===c?"":c;var d="";if(a.cssText||a.rules){var e=a.rules;if(e&&!_hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(e))for(var f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)d=Te(h,b,d);else b?b=a.cssText:(b=a.cssText,b=b.replace(Ue,"").replace(Ve,""),b=b.replace(We,"").replace(Xe,"")),(d=b.trim())&&(d="  "+d+"\n")}d&&(a.selector&&(c+=a.selector+" {\n"),c+=d,a.selector&&(c+="}\n\n"));return c}
function _hasMixinRules$$module$third_party$javascript$polymer$v2$shadycss$src$css_parse(a){a=a[0];return!!a&&!!a.selector&&0===a.selector.indexOf("--")}var Oe=/\/\*[^*]*\*+([^/*][^*]*\*+)*\//gim,Pe=/@import[^;]*;/gim,Ue=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?(?:[;\n]|$)/gim,Ve=/(?:^[^;\-\s}]+)?--[^;{}]*?:[^{};]*?{[^}]*?}(?:[;\n]|$)?/gim,We=/@apply\s*\(?[^);]*\)?\s*(?:[;\n]|$)?/gim,Xe=/[^;:]*?:[^;]*?var\([^;]*\)(?:[;\n]|$)?/gim,Se=/^@[^\s]*keyframes/,Re=/\s+/g;var Q=!(window.ShadyDOM&&window.ShadyDOM.inUse),Ye;function Ze(a){Ye=a&&a.shimcssproperties?!1:Q||!(navigator.userAgent.match(/AppleWebKit\/601|Edge\/15/)||!window.CSS||!CSS.supports||!CSS.supports("box-shadow","0 0 0 var(--foo)"))}var $e;window.ShadyCSS&&void 0!==window.ShadyCSS.cssBuild&&($e=window.ShadyCSS.cssBuild);window.ShadyCSS&&void 0!==window.ShadyCSS.nativeCss?Ye=window.ShadyCSS.nativeCss:window.ShadyCSS?(Ze(window.ShadyCSS),window.ShadyCSS=void 0):Ze(window.WebComponents&&window.WebComponents.flags);
var R=Ye,af=$e;var bf=/(?:^|[;\s{]\s*)(--[\w-]*?)\s*:\s*(?:((?:'(?:\\'|.)*?'|"(?:\\"|.)*?"|\([^)]*?\)|[^};{])+)|\{([^}]*)\}(?:(?=[;\s}])|$))/gi,cf=/(?:^|\W+)@apply\s*\(?([^);\n]*)\)?/gi,df=/(--[\w-]+)\s*([:,;)]|$)/gi,ef=/(animation\s*:)|(animation-name\s*:)/,ff=/@media\s(.*)/,gf=/\{[^}]*\}/g;var hf=new Set;function jf(a,b){if(!a)return"";"string"===typeof a&&(a=Ne(a));b&&kf(a,b);return Te(a,R)}function lf(a){!a.__cssRules&&a.textContent&&(a.__cssRules=Ne(a.textContent));return a.__cssRules||null}function mf(a){return!!a.parent&&7===a.parent.type}function kf(a,b,c,d){if(a){var e=!1,f=a.type;if(d&&4===f){var g=a.selector.match(ff);g&&(window.matchMedia(g[1]).matches||(e=!0))}1===f?b(a):c&&7===f?c(a):1E3===f&&(e=!0);if((a=a.rules)&&!e)for(e=0,f=a.length,g=void 0;e<f&&(g=a[e]);e++)kf(g,b,c,d)}}
function nf(a,b,c,d){var e=document.createElement("style");b&&e.setAttribute("scope",b);e.textContent=a;of(e,c,d);return e}var pf=null;function qf(a){a=document.createComment(" Shady DOM styles for "+a+" ");var b=document.head;b.insertBefore(a,(pf?pf.nextSibling:null)||b.firstChild);return pf=a}function of(a,b,c){b=b||document.head;b.insertBefore(a,c&&c.nextSibling||b.firstChild);pf?a.compareDocumentPosition(pf)===Node.DOCUMENT_POSITION_PRECEDING&&(pf=a):pf=a}
function rf(a,b){for(var c=0,d=a.length;b<d;b++)if("("===a[b])c++;else if(")"===a[b]&&0===--c)return b;return-1}function sf(a,b){var c=a.indexOf("var(");if(-1===c)return b(a,"","","");var d=rf(a,c+3),e=a.substring(c+4,d);c=a.substring(0,c);a=sf(a.substring(d+1),b);d=e.indexOf(",");return-1===d?b(c,e.trim(),"",a):b(c,e.substring(0,d).trim(),e.substring(d+1).trim(),a)}function tf(a,b){Q?a.setAttribute("class",b):window.ShadyDOM.nativeMethods.setAttribute.call(a,"class",b)}
function uf(a){var b=a.localName,c="";b?-1<b.indexOf("-")||(c=b,b=a.getAttribute&&a.getAttribute("is")||""):(b=a.is,c=a["extends"]);return{is:b,W:c}}function vf(a){for(var b=[],c="",d=0;0<=d&&d<a.length;d++)if("("===a[d]){var e=rf(a,d);c+=a.slice(d,e+1);d=e}else","===a[d]?(b.push(c),c=""):c+=a[d];c&&b.push(c);return b}
function wf(a){if(void 0!==af)return af;if(void 0===a.__cssBuild){var b=a.getAttribute("css-build");if(b)a.__cssBuild=b;else{a:{b="template"===a.localName?a.content.firstChild:a.firstChild;if(b instanceof Comment&&(b=b.textContent.trim().split(":"),"css-build"===b[0])){b=b[1];break a}b=""}if(""!==b){var c="template"===a.localName?a.content.firstChild:a.firstChild;c.parentNode.removeChild(c)}a.__cssBuild=b}}return a.__cssBuild||""}
function xf(a){a=void 0===a?"":a;return""!==a&&R?Q?"shadow"===a:"shady"===a:!1};function yf(){}function zf(a,b){var c=U;c.ea(a,function(a){c.element(a,b||"")})}m=yf.prototype;m.ea=function(a,b){a.nodeType===Node.ELEMENT_NODE&&b(a);if(a="template"===a.localName?(a.content||a._content||a).childNodes:a.children||a.childNodes)for(var c=0;c<a.length;c++)this.ea(a[c],b)};
m.element=function(a,b,c){if(b)if(a.classList)c?(a.classList.remove("style-scope"),a.classList.remove(b)):(a.classList.add("style-scope"),a.classList.add(b));else if(a.getAttribute){var d=a.getAttribute("class");c?d&&(b=d.replace("style-scope","").replace(b,""),tf(a,b)):tf(a,(d?d+" ":"")+"style-scope "+b)}};function Af(a,b,c){var d=U;d.ea(a,function(a){d.element(a,b,!0);d.element(a,c)})}function Bf(a,b){var c=U;c.ea(a,function(a){c.element(a,b||"",!0)})}
function Cf(a,b,c,d,e){var f=U;e=void 0===e?"":e;""===e&&(Q||"shady"===(void 0===d?"":d)?e=jf(b,c):(a=uf(a),e=Df(f,b,a.is,a.W,c)+"\n\n"));return e.trim()}function Df(a,b,c,d,e){var f=a.pa(c,d);c=a.Na(c);return jf(b,function(b){b.xc||(a.$a(b,a.Aa,c,f),b.xc=!0);e&&e(b,c,f)})}m.Na=function(a){return a?"."+a:""};m.pa=function(a,b){return b?"[is="+a+"]":a};m.$a=function(a,b,c,d){a.selector=a.j=this.ab(a,b,c,d)};
m.ab=function(a,b,c,d){var e=vf(a.selector);if(!mf(a)){a=0;for(var f=e.length,g=void 0;a<f&&(g=e[a]);a++)e[a]=b.call(this,g,c,d)}return e.filter(function(a){return!!a}).join(",")};m.cb=function(a){return a.replace(Ef,function(a,c,d){-1<d.indexOf("+")?d=d.replace(/\+/g,"___"):-1<d.indexOf("___")&&(d=d.replace(/___/g,"+"));return":"+c+"("+d+")"})};
m.Zb=function(a){for(var b=[],c;c=a.match(Ff);){var d=c.index,e=rf(a,d);if(-1===e)throw Error(c.input+" selector missing ')'");c=a.slice(d,e+1);a=a.replace(c,"\ue000");b.push(c)}return{Ga:a,matches:b}};m.cc=function(a,b){var c=a.split("\ue000");return b.reduce(function(a,b,f){return a+b+c[f+1]},c[0])};
m.Aa=function(a,b,c){var d=this,e=!1;a=a.trim();var f=Ef.test(a);f&&(a=a.replace(Ef,function(a,b,c){return":"+b+"("+c.replace(/\s/g,"")+")"}),a=this.cb(a));var g=Ff.test(a);if(g){var h=this.Zb(a);a=h.Ga;h=h.matches}a=a.replace(Gf,":host $1");a=a.replace(Hf,function(a,f,g){e||(a=d.ic(g,f,b,c),e=e||a.stop,f=a.oc,g=a.value);return f+g});g&&(a=this.cc(a,h));f&&(a=this.cb(a));return a};
m.ic=function(a,b,c,d){var e=a.indexOf("::slotted");0<=a.indexOf(":host")?a=this.kc(a,d):0!==e&&(a=c?this.bb(a,c):a);c=!1;0<=e&&(b="",c=!0);if(c){var f=!0;c&&(a=a.replace(If,function(a,b){return" > "+b}))}a=a.replace(Jf,function(a,b,c){return'[dir="'+c+'"] '+b+", "+b+'[dir="'+c+'"]'});return{value:a,oc:b,stop:f}};m.bb=function(a,b){a=a.split(/(\[.+?\])/);for(var c=[],d=0;d<a.length;d++)if(1===d%2)c.push(a[d]);else{var e=a[d];if(""!==e||d!==a.length-1)e=e.split(":"),e[0]+=b,c.push(e.join(":"))}return c.join("")};
m.kc=function(a,b){var c=a.match(Kf);return(c=c&&c[2].trim()||"")?c[0].match(Lf)?a.replace(Kf,function(a,c,f){return b+f}):c.split(Lf)[0]===b?c:"should_not_match":a.replace(":host",b)};function Mf(a){":root"===a.selector&&(a.selector="html")}m.jc=function(a){return a.match(":host")?"":a.match("::slotted")?this.Aa(a,":not(.style-scope)"):this.bb(a.trim(),":not(.style-scope)")};da.Object.defineProperties(yf.prototype,{X:{configurable:!0,enumerable:!0,get:function(){return"style-scope"}}});
var Ef=/:(nth[-\w]+)\(([^)]+)\)/,Hf=/(^|[\s>+~]+)((?:\[.+?\]|[^\s>+~=[])+)/g,Lf=/[[.:#*]/,Gf=/^(::slotted)/,Kf=/(:host)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,If=/(?:::slotted)(?:\(((?:\([^)(]*\)|[^)(]*)+?)\))/,Jf=/(.*):dir\((?:(ltr|rtl))\)/,Ff=/:(?:matches|any|-(?:webkit|moz)-any)/,U=new yf;function Nf(a,b,c,d,e){this.A=a||null;this.placeholder=b||null;this.Ea=c||[];this.M=null;this.cssBuild=e||"";this.W=d||"";this.J=this.m=this.H=null}function V(a){return a?a.__styleInfo:null}function Of(a,b){return a.__styleInfo=b}Nf.prototype.Ob=function(){return this.A};Nf.prototype._getStyleRules=Nf.prototype.Ob;function Pf(a){var b=this.matches||this.matchesSelector||this.mozMatchesSelector||this.msMatchesSelector||this.oMatchesSelector||this.webkitMatchesSelector;return b&&b.call(this,a)}var Qf=navigator.userAgent.match("Trident");function Rf(){}function Sf(a){var b={},c=[],d=0;kf(a,function(a){Tf(a);a.index=d++;a=a.g.cssText;for(var c;c=df.exec(a);){var e=c[1];":"!==c[2]&&(b[e]=!0)}},function(a){c.push(a)});a.Qb=c;a=[];for(var e in b)a.push(e);return a}
function Tf(a){if(!a.g){var b={},c={};Uf(a,c)&&(b.w=c,a.rules=null);b.cssText=a.parsedCssText.replace(gf,"").replace(bf,"");a.g=b}}function Uf(a,b){var c=a.g;if(c){if(c.w)return Object.assign(b,c.w),!0}else{c=a.parsedCssText;for(var d;a=bf.exec(c);){d=(a[2]||a[3]).trim();if("inherit"!==d||"unset"!==d)b[a[1].trim()]=d;d=!0}return d}}
function Vf(a,b,c){b&&(b=0<=b.indexOf(";")?Wf(a,b,c):sf(b,function(b,e,f,g){if(!e)return b+g;(e=Vf(a,c[e],c))&&"initial"!==e?"apply-shim-inherit"===e&&(e="inherit"):e=Vf(a,c[f]||f,c)||f;return b+(e||"")+g}));return b&&b.trim()||""}
function Wf(a,b,c){b=b.split(";");for(var d=0,e,f;d<b.length;d++)if(e=b[d]){cf.lastIndex=0;if(f=cf.exec(e))e=Vf(a,c[f[1]],c);else if(f=e.indexOf(":"),-1!==f){var g=e.substring(f);g=g.trim();g=Vf(a,g,c)||g;e=e.substring(0,f)+g}b[d]=e&&e.lastIndexOf(";")===e.length-1?e.slice(0,-1):e||""}return b.join(";")}
function Xf(a,b){var c={},d=[];kf(a,function(a){a.g||Tf(a);var e=a.j||a.parsedSelector;b&&a.g.w&&e&&Pf.call(b,e)&&(Uf(a,c),a=a.index,e=parseInt(a/32,10),d[e]=(d[e]||0)|1<<a%32)},null,!0);return{w:c,key:d}}
function Yf(a,b,c,d){b.g||Tf(b);if(b.g.w){var e=uf(a);a=e.is;e=e.W;e=a?U.pa(a,e):"html";var f=b.parsedSelector,g=":host > *"===f||"html"===f,h=0===f.indexOf(":host")&&!g;"shady"===c&&(g=f===e+" > *."+e||-1!==f.indexOf("html"),h=!g&&0===f.indexOf(e));if(g||h)c=e,h&&(b.j||(b.j=U.ab(b,U.Aa,U.Na(a),e)),c=b.j||e),d({Ga:c,wc:h,Zc:g})}}function Zf(a,b,c){var d={},e={};kf(b,function(b){Yf(a,b,c,function(c){Pf.call(a._element||a,c.Ga)&&(c.wc?Uf(b,d):Uf(b,e))})},null,!0);return{Dc:e,vc:d}}
function $f(a,b,c,d){var e=uf(b),f=U.pa(e.is,e.W),g=new RegExp("(?:^|[^.#[:])"+(b["extends"]?"\\"+f.slice(0,-1)+"\\]":f)+"($|[.:[\\s>+~])"),h=V(b);e=h.A;h=h.cssBuild;var k=a.Fb(b,e,d);return Cf(b,e,function(b){var e="";b.g||Tf(b);b.g.cssText&&(e=Wf(a,b.g.cssText,c));b.cssText=e;if(!Q&&!mf(b)&&b.cssText){var h=e=b.cssText;null==b.gb&&(b.gb=ef.test(e));if(b.gb)if(null==b.ja){b.ja=[];for(var l in k)h=k[l],h=h(e),e!==h&&(e=h,b.ja.push(l))}else{for(l=0;l<b.ja.length;++l)h=k[b.ja[l]],e=h(e);h=e}b.cssText=
h;a.gc(b,g,f,d)}},h)}Rf.prototype.Fb=function(a,b,c){a=b.Qb;b={};if(!Q&&a)for(var d=0,e=a[d];d<a.length;e=a[++d])this.fc(e,c),b[e.keyframesName]=this.Rb(e);return b};Rf.prototype.Rb=function(a){return function(b){return b.replace(a.yc,a.nb)}};Rf.prototype.fc=function(a,b){a.yc=new RegExp("\\b"+a.keyframesName+"(?!\\B|-)","g");a.nb=a.keyframesName+"-"+b;a.j=a.j||a.selector;a.selector=a.j.replace(a.keyframesName,a.nb)};
Rf.prototype.gc=function(a,b,c,d){a.j=a.j||a.selector;d="."+d;for(var e=vf(a.j),f=0,g=e.length,h=void 0;f<g&&(h=e[f]);f++)e[f]=h.match(b)?h.replace(c,d):d+" "+h;a.selector=e.join(",")};function ag(a,b){var c=bg,d=lf(a);a.textContent=jf(d,function(a){var d=a.cssText=a.parsedCssText;a.g&&a.g.cssText&&(d=d.replace(Ue,"").replace(Ve,""),a.cssText=Wf(c,d,b))})}da.Object.defineProperties(Rf.prototype,{pb:{configurable:!0,enumerable:!0,get:function(){return"x-scope"}}});var bg=new Rf;var cg={},dg=window.customElements;if(dg&&!Q){var eg=dg.define;dg.define=function(a,b,c){cg[a]||(cg[a]=qf(a));eg.call(dg,a,b,c)}};function fg(){this.cache={};this.Jc=100}fg.prototype.nc=function(a,b,c){for(var d=0;d<c.length;d++){var e=c[d];if(a.w[e]!==b[e])return!1}return!0};fg.prototype.store=function(a,b,c,d){var e=this.cache[a]||[];e.push({w:b,styleElement:c,m:d});e.length>this.Jc&&e.shift();this.cache[a]=e};fg.prototype.fetch=function(a,b,c){if(a=this.cache[a])for(var d=a.length-1;0<=d;d--){var e=a[d];if(this.nc(e,b,c))return e}};function gg(){}var hg=new RegExp(U.X+"\\s*([^\\s]*)");function ig(a){return(a=(a.classList&&a.classList.value?a.classList.value:a.getAttribute("class")||"").match(hg))?a[1]:""}function jg(a){var b=a.getRootNode();return b===a||b===a.ownerDocument?"":(a=b.host)?uf(a).is:""}
function kg(a){for(var b=0;b<a.length;b++){var c=a[b];if(c.target!==document.documentElement&&c.target!==document.head)for(var d=0;d<c.addedNodes.length;d++){var e=c.addedNodes[d];if(e.nodeType===Node.ELEMENT_NODE){var f=e.getRootNode(),g=ig(e);if(g&&f===e.ownerDocument&&("style"!==e.localName&&"template"!==e.localName||""===wf(e)))Bf(e,g);else if(f instanceof ShadowRoot)for(f=jg(e),f!==g&&Af(e,g,f),e=window.ShadyDOM.nativeMethods.querySelectorAll.call(e,":not(."+U.X+")"),g=0;g<e.length;g++){f=e[g];
var h=jg(f);h&&U.element(f,h)}}}}}
if(!(Q||window.ShadyDOM&&window.ShadyDOM.handlesDynamicScoping)){var lg=new MutationObserver(kg),mg=function(a){lg.observe(a,{childList:!0,subtree:!0})};if(window.customElements&&!window.customElements.polyfillWrapFlushCallback)mg(document);else{var ng=function(){mg(document.body)};window.HTMLImports?window.HTMLImports.whenReady(ng):requestAnimationFrame(function(){if("loading"===document.readyState){var a=function(){ng();document.removeEventListener("readystatechange",a)};document.addEventListener("readystatechange",
a)}else ng()})}gg=function(){kg(lg.takeRecords())}}var og=gg;var pg={};var qg=Promise.resolve();function rg(a){if(a=pg[a])a._applyShimCurrentVersion=a._applyShimCurrentVersion||0,a._applyShimValidatingVersion=a._applyShimValidatingVersion||0,a._applyShimNextVersion=(a._applyShimNextVersion||0)+1}function sg(a){return a._applyShimCurrentVersion===a._applyShimNextVersion}function tg(a){a._applyShimValidatingVersion=a._applyShimNextVersion;a._validating||(a._validating=!0,qg.then(function(){a._applyShimCurrentVersion=a._applyShimNextVersion;a._validating=!1}))};var ug=new fg;function W(){this.Ya={};this.P=document.documentElement;var a=new Me;a.rules=[];this.C=Of(this.P,new Nf(a));this.sa=!1;this.i=this.h=null}m=W.prototype;m.flush=function(){og()};m.Lb=function(a){var b=this.Ya[a]=(this.Ya[a]||0)+1;return a+"-"+b};m.sc=function(a){return lf(a)};m.Ic=function(a){return jf(a)};
m.Kb=function(a){var b=[];a=a.content.querySelectorAll("style");for(var c=0;c<a.length;c++){var d=a[c];if(d.hasAttribute("shady-unscoped")){if(!Q){var e=d.textContent;hf.has(e)||(hf.add(e),e=d.cloneNode(!0),document.head.appendChild(e));d.parentNode.removeChild(d)}}else b.push(d.textContent),d.parentNode.removeChild(d)}return b.join("").trim()};m.prepareTemplate=function(a,b,c){this.prepareTemplateDom(a,b);this.prepareTemplateStyles(a,b,c)};
m.prepareTemplateStyles=function(a,b,c){if(!a._prepared){Q||cg[b]||(cg[b]=qf(b));a._prepared=!0;a.name=b;a["extends"]=c;pg[b]=a;var d=wf(a),e=xf(d);c={is:b,"extends":c};var f=this.Kb(a);this.R();if(!e){var g;if(g=!d)g=cf.test(f)||bf.test(f),cf.lastIndex=0,bf.lastIndex=0;var h=Ne(f);g&&R&&this.h&&this.h.transformRules(h,b);a._styleAst=h}g=[];R||(g=Sf(a._styleAst));if(!g.length||R)b=this.Mb(c,a._styleAst,Q?a.content:null,cg[b]||null,d,e?f:""),a._style=b;a.Xb=g}};
m.prepareTemplateDom=function(a,b){var c=wf(a);Q||"shady"===c||a._domPrepared||(a._domPrepared=!0,zf(a.content,b))};m.Mb=function(a,b,c,d,e,f){f=Cf(a,b,null,e,f);return f.length?nf(f,a.is,c,d):null};m.Yb=function(a){var b=uf(a),c=b.is;b=b.W;var d=cg[c]||null;c=pg[c];if(c){var e=c._styleAst;var f=c.Xb;var g=wf(c)}e=new Nf(e,d,f,b,g);c&&Of(a,e);return e};m.Gb=function(){!this.h&&window.ShadyCSS&&window.ShadyCSS.ApplyShim&&(this.h=window.ShadyCSS.ApplyShim,this.h.invalidCallback=rg)};
m.Hb=function(){var a=this;!this.i&&window.ShadyCSS&&window.ShadyCSS.CustomStyleInterface&&(this.i=window.ShadyCSS.CustomStyleInterface,this.i.transformCallback=function(b){a.mb(b)},this.i.validateCallback=function(){requestAnimationFrame(function(){(a.i.enqueued||a.sa)&&a.flushCustomStyles()})})};m.R=function(){this.Gb();this.Hb()};
m.flushCustomStyles=function(){this.R();if(this.i){var a=this.i.processStyles();this.i.enqueued&&!xf(this.C.cssBuild)&&(R?this.C.cssBuild||this.ec(a):(this.eb(this.P,this.C),this.xb(a),this.sa&&this.styleDocument()),this.i.enqueued=!1)}};
m.styleElement=function(a,b){var c=V(a);c||(c=this.Yb(a));this.ua(a)||(this.sa=!0);b&&(c.M=c.M||{},Object.assign(c.M,b));if(R){b=c;c=uf(a).is;if(b.M){var d=b.M,e;for(e in d)null===e?a.style.removeProperty(e):a.style.setProperty(e,d[e])}if(((e=pg[c])||this.ua(a))&&(!e||""===wf(e))&&e&&e._style&&!sg(e)){if(sg(e)||e._applyShimValidatingVersion!==e._applyShimNextVersion)this.R(),this.h&&this.h.transformRules(e._styleAst,c),e._style.textContent=Cf(a,b.A),tg(e);Q&&(c=a.shadowRoot)&&(c=c.querySelector("style"))&&
(c.textContent=Cf(a,b.A));b.A=e._styleAst}}else b=c,this.flush(),this.eb(a,b),b.Ea&&b.Ea.length&&this.yb(a,b)};m.za=function(a){return(a=a.getRootNode().host)?V(a)?a:this.za(a):this.P};m.ua=function(a){return a===this.P};
m.yb=function(a,b){var c=uf(a).is,d=ug.fetch(c,b.H,b.Ea),e=d?d.styleElement:null,f=b.m;b.m=d&&d.m||this.Lb(c);var g=b.m;var h=bg;h=e?e.textContent||"":$f(h,a,b.H,g);var k=V(a),l=k.J;l&&!Q&&l!==e&&(l._useCount--,0>=l._useCount&&l.parentNode&&l.parentNode.removeChild(l));Q?k.J?(k.J.textContent=h,e=k.J):h&&(e=nf(h,g,a.shadowRoot,k.placeholder)):e?e.parentNode||(Qf&&-1<h.indexOf("@media")&&(e.textContent=h),of(e,null,k.placeholder)):h&&(e=nf(h,g,null,k.placeholder));e&&(e._useCount=e._useCount||0,k.J!=
e&&e._useCount++,k.J=e);g=e;Q||(e=b.m,k=h=a.getAttribute("class")||"",f&&(k=h.replace(new RegExp("\\s*x-scope\\s*"+f+"\\s*","g")," ")),k+=(k?" ":"")+"x-scope "+e,h!==k&&tf(a,k));d||ug.store(c,b.H,g,b.m);return g};m.eb=function(a,b){var c=this.za(a),d=V(c);c=Object.create(d.H||null);var e=Zf(a,b.A,b.cssBuild);a=Xf(d.A,a).w;Object.assign(c,e.vc,a,e.Dc);this.Ub(c,b.M);a=bg;e=Object.getOwnPropertyNames(c);d=0;for(var f;d<e.length;d++)f=e[d],c[f]=Vf(a,c[f],c);b.H=c};
m.Ub=function(a,b){for(var c in b){var d=b[c];if(d||0===d)a[c]=d}};m.styleDocument=function(a){this.styleSubtree(this.P,a)};m.styleSubtree=function(a,b){var c=a.shadowRoot;(c||this.ua(a))&&this.styleElement(a,b);if(b=c&&(c.children||c.childNodes))for(a=0;a<b.length;a++)this.styleSubtree(b[a]);else if(a=a.children||a.childNodes)for(b=0;b<a.length;b++)this.styleSubtree(a[b])};m.ec=function(a){for(var b=0;b<a.length;b++){var c=this.i.getStyleForCustomStyle(a[b]);c&&this.dc(c)}};
m.xb=function(a){for(var b=0;b<a.length;b++){var c=this.i.getStyleForCustomStyle(a[b]);c&&ag(c,this.C.H)}};m.mb=function(a){var b=this,c=wf(a);c!==this.C.cssBuild&&(this.C.cssBuild=c);if(!xf(c)){var d=lf(a);kf(d,function(a){if(Q)Mf(a);else{var d=U;a.selector=a.parsedSelector;Mf(a);d.$a(a,d.jc)}R&&""===c&&(b.R(),b.h&&b.h.transformRule(a))});R?a.textContent=jf(d):this.C.A.rules.push(d)}};m.dc=function(a){if(R&&this.h){var b=lf(a);this.R();this.h.transformRules(b);a.textContent=jf(b)}};
m.getComputedStyleValue=function(a,b){var c;R||(c=(V(a)||V(this.za(a))).H[b]);return(c=c||window.getComputedStyle(a).getPropertyValue(b))?c.trim():""};m.Hc=function(a,b){var c=a.getRootNode();b=b?b.split(/\s/):[];c=c.host&&c.host.localName;if(!c){var d=a.getAttribute("class");if(d){d=d.split(/\s/);for(var e=0;e<d.length;e++)if(d[e]===U.X){c=d[e+1];break}}}c&&b.push(U.X,c);R||(c=V(a))&&c.m&&b.push(bg.pb,c.m);tf(a,b.join(" "))};m.hc=function(a){return V(a)};m.Gc=function(a,b){U.element(a,b)};
m.Kc=function(a,b){U.element(a,b,!0)};m.Fc=function(a){return jg(a)};m.pc=function(a){return ig(a)};W.prototype.flush=W.prototype.flush;W.prototype.prepareTemplate=W.prototype.prepareTemplate;W.prototype.styleElement=W.prototype.styleElement;W.prototype.styleDocument=W.prototype.styleDocument;W.prototype.styleSubtree=W.prototype.styleSubtree;W.prototype.getComputedStyleValue=W.prototype.getComputedStyleValue;W.prototype.setElementClass=W.prototype.Hc;W.prototype._styleInfoForNode=W.prototype.hc;
W.prototype.transformCustomStyleForDocument=W.prototype.mb;W.prototype.getStyleAst=W.prototype.sc;W.prototype.styleAstToString=W.prototype.Ic;W.prototype.flushCustomStyles=W.prototype.flushCustomStyles;W.prototype.scopeNode=W.prototype.Gc;W.prototype.unscopeNode=W.prototype.Kc;W.prototype.scopeForNode=W.prototype.Fc;W.prototype.currentScopeForNode=W.prototype.pc;Object.defineProperties(W.prototype,{nativeShadow:{get:function(){return Q}},nativeCss:{get:function(){return R}}});var Y=new W,vg,wg;window.ShadyCSS&&(vg=window.ShadyCSS.ApplyShim,wg=window.ShadyCSS.CustomStyleInterface);
window.ShadyCSS={ScopingShim:Y,prepareTemplate:function(a,b,c){Y.flushCustomStyles();Y.prepareTemplate(a,b,c)},prepareTemplateDom:function(a,b){Y.prepareTemplateDom(a,b)},prepareTemplateStyles:function(a,b,c){Y.flushCustomStyles();Y.prepareTemplateStyles(a,b,c)},styleSubtree:function(a,b){Y.flushCustomStyles();Y.styleSubtree(a,b)},styleElement:function(a){Y.flushCustomStyles();Y.styleElement(a)},styleDocument:function(a){Y.flushCustomStyles();Y.styleDocument(a)},flushCustomStyles:function(){Y.flushCustomStyles()},
getComputedStyleValue:function(a,b){return Y.getComputedStyleValue(a,b)},nativeCss:R,nativeShadow:Q,cssBuild:af};vg&&(window.ShadyCSS.ApplyShim=vg);wg&&(window.ShadyCSS.CustomStyleInterface=wg);var xg=window.customElements,yg=window.HTMLImports,zg=window.HTMLTemplateElement;window.WebComponents=window.WebComponents||{};if(xg&&xg.polyfillWrapFlushCallback){var Ag,Bg=function(){if(Ag){zg.D&&zg.D(window.document);var a=Ag;Ag=null;a();return!0}},Cg=yg.whenReady;xg.polyfillWrapFlushCallback(function(a){Ag=a;Cg(Bg)});yg.whenReady=function(a){Cg(function(){Bg()?yg.whenReady(a):a()})}}
yg.whenReady(function(){requestAnimationFrame(function(){window.WebComponents.ready=!0;document.dispatchEvent(new CustomEvent("WebComponentsReady",{bubbles:!0}))})});var Dg=document.createElement("style");Dg.textContent="body {transition: opacity ease-in 0.2s; } \nbody[unresolved] {opacity: 0; display: block; overflow: hidden; position: relative; } \n";var Eg=document.querySelector("head");Eg.insertBefore(Dg,Eg.firstChild);})();
//# sourceMappingURL=webcomponents-lite.js.map
